### ISSUE TITLE
Slider thumb alignment in Android 5.0  API 21.

### ISSUE THREAD

**Issue by YajanaRao** [callstack/react-native-slider#107]
## Environment

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 1.08 GB / 7.89 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.3.2 - C:\Users\admin\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.1 - C:\watchman.EXE
  SDKs:
    Android SDK:
      Android NDK: 20.0.5594570

## Description
Thumb alignment is not proper in android version 5 and API 21.

## Reproducible Demo
![image](https://user-images.githubusercontent.com/38914337/65157598-94302c00-da4e-11e9-8be3-87bc733bed23.png)

``` js

 <Slider
    style={{width: 200, height: 40}}
    minimumValue={0}
    maximumValue={1}
    minimumTrackTintColor="#FFFFFF"
    maximumTrackTintColor="#000000"/>

```

**Comment by schumannd** [comment]
Same thing is happening when using `thumbImage` on iOS. The Thumb is off set by ~half of the image width

**Comment by BartoszKlonowski** [comment]
Hello @YajanaRao!
As I can see the latest release does have the thumb aligned exactly in the middle of the track.
Can you verify it on your side using the latest version (*v4.1.6*)?

**Comment by YajanaRao** [comment]
I don't have android version 5 setup now. I will those this ticket, if any one face this issue again can reopen the ticket.

**Comment by BartoszKlonowski** [comment]
Thank you for the response @YajanaRao!
