### ISSUE TITLE
Same Image for ThumbImage Looks Drastically on Different Platforms

### ISSUE THREAD

**Issue by bobber205** [callstack/react-native-slider#112]
Related to: https://github.com/react-native-community/react-native-slider/issues/97

I'm attaching two images, first is iOS with the thumb image looking great.
I love the support for Android but the image is SO small.

![image](https://user-images.githubusercontent.com/5841107/66336993-18a9f800-e8f3-11e9-8ba3-c2f1423174a9.png)

![image](https://user-images.githubusercontent.com/5841107/66337103-56a71c00-e8f3-11e9-9019-235e55d0b7b5.png)

Anything other than using a different image for Android work?

**Comment by BartoszKlonowski** [comment]
Dears,
as I'm already assigned to #559, which is a duplicate of this one, I will close this in favor of the superior.
Please track the progress in the duplicate.
Thank you!
