### ISSUE TITLE
drawable android:drawable/seekbar thumb material anim with resource id#0x1080688

### ISSUE THREAD

**Issue by santanu07** [callstack/react-native-slider#149]
when I was working on react native video with slider 

It gives error with 
drawable android:drawable/seekbar thumb material anim with resource id#0x1080688

**Comment by MBakhtiyor** [comment]
+1

**Comment by MisterFredy** [comment]
im still looking this issue

**Comment by maheshsgr** [comment]
Fatal Exception: android.content.res.Resources$NotFoundException: Drawable android:drawable/seekbar_thumb_material_anim with resource ID #0x10806a7

**Comment by idemax** [comment]
Check this comment: https://github.com/facebook/react-native/issues/17560#issuecomment-405518992

**Comment by BartoszKlonowski** [comment]
Hello @santanu07!
I can't reproduce your issue as there's no repro given in your report.
Can you check if the same error happens with the latest release (*v4.1.6*)?

**Comment by BartoszKlonowski** [comment]
Closing due to issue being outdated and no response from an author.
