### ISSUE TITLE
How to add style for slider steps ?

### ISSUE THREAD

**Issue by mustapha-ghlissi** [callstack/react-native-slider#157]
Hi every body,

I am looking for a way to add custom style to slider steps (e.g: 3 steps)

for example a small circle in each step 

Any solution for that ? 

Regards

**Comment by Sharcoux** [comment]
Check @sharcoux/slider 3.2.0, Tell me if it answer your needs.
I'm trying to make a cross platform project for RN and RNWeb.

**Comment by jimmi-joensson** [comment]
This would be a great addition

**Comment by BartoszKlonowski** [comment]
@jimmi-joensson I agree!
I believe this feature should come in pair with #71.
