### ISSUE TITLE
Touch to seek does not work on iOS

### ISSUE THREAD

**Issue by LisaKr** [callstack/react-native-slider#159]
## Environment

  ```
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 27.41 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
## Description
Contrary to Android, the "tap to seek" behavior is not working on iOS. Tapping on the slider does not make the video seek to the tapped moment, but instead the handler jumps back to the previous position. 
![Kapture 2020-03-09 at 15 00 28](https://user-images.githubusercontent.com/11159684/76219859-cb6de180-6216-11ea-84a8-43146519f9ea.gif)

I have tried the solution suggested in this PR (https://github.com/react-native-community/react-native-slider/pull/117) and it works, but my changes to the `RNCSlider.m` file stay local in the `node_modules`. For some reason this PR providing a solution was reverted, so it is not a part of the library. Any chance this functionality can be added or somehow enabled? 

Thanks!

**Comment by LisaKr** [comment]
I think the problem is that I'm using the version `1.1.4` (as I am also using `react-native 0.59.10`)and the fix only came in `2.0.7`... 🤦‍♀

**Comment by Jason-Cooke** [comment]
I can confirm that the problem still persists in versions **2.0.8** and **2.0.9**

**Comment by BartoszKlonowski** [comment]
Hello @LisaKr!
In the latest release (*v4.1.6*) the `tapToSeek` property is working well and you are using the outdated v3.0.3.
Can you verify if your issue still occurs on the latest version?

**Comment by richardwu** [comment]
> Hello @LisaKr!
> In the latest release (_v4.1.6_) the `tapToSeek` property is working well and you are using the outdated v3.0.3.
> Can you verify if your issue still occurs on the latest version?

FWIW it 4.1.6 (vs 4.1.3) fixed it for me, thanks!

**Comment by BartoszKlonowski** [comment]
Thanks for the confirmation @richardwu!
I will close this issue as it is already fixed and there's no feedback from an author.
