### ISSUE TITLE
android build failed,  run successfully  on ios

### ISSUE THREAD

**Issue by Akshayagt20** [callstack/react-native-slider#167]
> Could not resolve all artifacts for configuration ':react-native-community_slider:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.2.0.
     Required by:
         project :react-native-community_slider > com.android.tools.build:gradle:3.2.1 > com.android.tools.lint:lint-gradle-api:26.2.1
         project :react-native-community_slider > com.android.tools.build:gradle:3.2.1 > com.android.tools.build:builder:3.2.1 > com.android.tools:sdk-common:26.2.1
      > No cached version of org.jetbrains.kotlin:kotlin-reflect:1.2.0 available for offline mode.
      > No cached version of org.jetbrains.kotlin:kotlin-reflect:1.2.0 available for offline mode.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.71.
     Required by:
         project :react-native-community_slider > com.android.tools.build:gradle:3.2.1 > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71
         project :react-native-community_slider > com.android.tools.build:gradle:3.2.1 > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 > org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.71
      > No cached version of org.jetbrains.kotlin:kotlin-stdlib:1.2.71 available for offline mode.
      > No cached version of org.jetbrains.kotlin:kotlin-stdlib:1.2.71 available for offline mode.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.2.71.
     Required by:
         project :react-native-community_slider > com.android.tools.build:gradle:3.2.1 > com.android.tools.build.jetifier:jetifier-core:1.0.0-alpha10
         project :react-native-community_slider > com.android.tools.build:gradle:3.2.1 > com.android.tools.build.jetifier:jetifier-processor:1.0.0-alpha10
      > No cached version of org.jetbrains.kotlin:kotlin-stdlib:1.2.71 available for offline mode.
      > No cached version of org.jetbrains.kotlin:kotlin-stdlib:1.2.71 available for offline mode.

versions:
    "@react-native-community/slider": "^2.0.9",
    "react-native": "0.61.5",
     node : 12.16.1
    npm : 6.13.4

**Comment by ksetrin** [comment]
The same problem

Some logs
```

% npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1219 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Task :app:transformDexArchiveWithDexMergerForDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
248 actionable tasks: 2 executed, 246 up-to-date
D8: Cannot fit requested classes in a single dex file (# fields: 66250 > 65536)
java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

```

**Comment by ksetrin** [comment]
I find out a [temporary workaround ](https://github.com/facebook/react-native/issues/27362#issuecomment-579809148)

just add this in android/app/build.gradle
```
android{
defaultConfig{
  .......
 multiDexEnabled true 
  }
}
```

**Comment by BartoszKlonowski** [comment]
@Akshayagt20 I can see this error is reported for an outdated version 2.0.9. Have you tried it on the latest one: 3.0.3?
Please double check if you are unblocked with the build using latest version.

**Comment by BartoszKlonowski** [comment]
Closing due to no author's feedback.
