### ISSUE TITLE
Add thumbSize as a prop (or even thumbStyle)

### ISSUE THREAD

**Issue by CezarCobuz** [callstack/react-native-slider#169]
## Only **thumbTintColor** offers too little flexibility - thumbSize is needed

The size of the thumb can NOT be controlled without affecting the whole slider. On **iOS** the thumb is significantly **bigger** than on Android. Even by adding a thumb image scales different from one platform to another. At this point there is no way to apply a fixed thumb size for consistency over the two platforms.

**Comment by Sharcoux** [comment]
[this PR](https://github.com/react-native-community/react-native-slider/pull/165) takes care of this for the web implementation if it gets merged. There would be only the native implementation to be done.

**Comment by Sharcoux** [comment]
By the way, there could be a quick fix for this: the web implementation should be working perfectly fine for native too, so we could just use the web implementation as the universal implementation. What do you think @michalchudziak ? Of course we would need to ensure that no feature provided by the current native implementation is missing. But is this a path that would be acceptable?

**Comment by Sharcoux** [comment]
@michalchudziak? Your opinion about it?

**Comment by n0umankhan** [comment]
+1

**Comment by kevinhylant** [comment]
Curious where this stands for mobile - would be a helpful feature. Thanks for your contributions toward it!

**Comment by Sharcoux** [comment]
Actually I'm working on a fully compatible RN + RNWeb version with all the pending feature request I found here. I'm just having some trouble finding some time these 2 weeks to conclude it but you can give it a try. It is npm i -S @sharcoux/slider
If you encounter any trouble you can tell me. It will make me save time when I'm finishing it.

**Comment by TN-Figueiredo** [comment]
+1

**Comment by nickarora** [comment]
The lack of traction on this issue is surprising to me; This seems critical for anyone who intends to use this slider across multiple platforms and cares for consistency...

**Comment by Sharcoux** [comment]
Could you give a try at @sharcoux/slider?

**Comment by agnieszkabugla** [comment]
+1

**Comment by ShivamJoker** [comment]
Please we need a fix thumb value for android and ios

**Comment by arthur-vargas** [comment]
+1

**Comment by raphaelrupprecht** [comment]
+1

**Comment by Sharcoux** [comment]
@raphaelrupprecht @arthur-vargas @ShivamJoker if you need something for now, just try @sharcoux/slider from npm. It is open source and used and maintained by my company. You can ask if you have issues.

**Comment by TowhidKashem** [comment]
In addition to thumbsize support another deal breaker is the ghastly box shadow thats on the thumb handle by default. There should be a way to remove that or just support style prop and call it a day!

**Comment by AlisanCakir** [comment]
+1

**Comment by yamila-fraiman** [comment]
+1

**Comment by ludvigeriksson** [comment]
+1

**Comment by SamiChab** [comment]
+1

**Comment by brunoleitem** [comment]
+1

**Comment by vietnt-uet** [comment]
+1

**Comment by mhackeras** [comment]
+1

**Comment by artfxx** [comment]
+ 1

**Comment by OneTuskedMario** [comment]
+1

**Comment by mguyard** [comment]
Hello,

I've also this issue. Something is already in progress to allow this ? Thanks

**Comment by BartoszKlonowski** [comment]
I would like to keep it as one feature request opened in #40.
I will close this one, but please keep the track in the mentioned issue.

**Comment by DrStoop** [comment]
+1

**Comment by DrStoop** [comment]
### Quick Wanna-Be-Fix

Anyone who want to stick to the native sliders and only needs to adjust their thumb size by 10-20% at max, can have a look this short workaround. It provides the following:

- rescales the entire slider based on the `thumbSize` prop, meaning the thumb AND the track will be resized
- `thumbSize` tries to approximate the wanted pixel size for iOS and Android, but obviously it's just a hack
- rescaling leads to unwanted padding effects which can be compensated for on the "critical side" with `alignScaledSlider`
- I experienced some buggy thumb jumping effects after fast sliding gestures. I don't know if that was due to my own code, but `ScaledSlider` also fixes that - in case you also encountered those issues...
- all `SliderProps` are fully functional, just be careful with the `style` prop

Hopefully that's helpful for some of you, it's doing the job for me... enjoy! 

```ts
import Slider, { SliderProps } from "@react-native-community/slider";
import React, { useCallback, useMemo, useState } from "react";
import { LayoutChangeEvent, Platform, StyleProp, StyleSheet, View, ViewStyle } from "react-native";

type ScaledSliderAlignment = "left" | "center" | "right"

export interface ScaledSliderProps extends SliderProps {
  /**
   * The scaled slider shows a unwanted padding effect when scaled.
   * Choose the alignment to compensate for this effect on the chossen side,
   * e.g. when alignScaledSlider="right", the slider will show no unwanted padding
   *  to the right.
   * @default "center"
   */
  alignScaledSlider?: ScaledSliderAlignment
  /**
   * Approximated size of the thumb in pixels.
   * HACKTTENTION: The thumb size also affects the the slider length & height!!!
   * These effects will have to be accounted for during styling... it's just a hack.
   */
  thumbSize?: number
}

// This defines how well the `thumbSize` prop approximates the actual pixel value.
// In case you realize e.g. that the thumb appears smaller than `thumbSize` decrease
// `defaultThumbSize...` slightly.
const defaultThumbSize = Platform.OS === "android" ? 15 : 20;

export const ScaledSlider: React.FC<ScaledSliderProps> = (props) => {
  const {
    alignScaledSlider = "center",
    onSlidingComplete,
    style,
    thumbSize,
    value,
    ...restProps
  } = props

  const [sliderValue, setSliderValue] = useState<number | undefined>(value)
  const [sliderWidth, setSliderWidth] = useState<number | undefined>(undefined)

  // Scale with which the slider will be transformed
  const scale: number = useMemo(() => thumbSize
    ? thumbSize / defaultThumbSize
    : 1,
    [thumbSize])

  const $flattenedStyle = useMemo(() => StyleSheet.flatten(style), [style])

  const _onLayout = useCallback((event: LayoutChangeEvent) => {
    setSliderWidth(event.nativeEvent.layout.width)
  }, [])

  // BUGFIX: On fast sliding, the slider does not jump around anymore after sliding is completed
  const _onSlidingComplete = useCallback((val: number) => {
    setSliderValue(val)
    onSlidingComplete?.(val)
  }, [value])

  // After scaling, the slider shows unwanted padding effects which can be compensated at 
  // least on one side that can be chosen by `alignScaledSlider`.
  const $paddingCompensation: ViewStyle = useMemo(() => (alignScaledSlider !== "center"
    ? {
      [alignScaledSlider]: (sliderWidth !== undefined
        ? - sliderWidth * (1 - scale) / 2 // compensation for unwanted "padding-effect" from scaling
        : 0) + (typeof $flattenedStyle.right === 'number' ? $flattenedStyle.right : 0),
    }
    : {}
  ), [sliderWidth, scale, style])

  const $style: StyleProp<ViewStyle> = useMemo(() => ([{
    ...$paddingCompensation,
    transform: [{ scale }],
    width: "40%"
  }, style, { width: "100%" }]
  ), [sliderWidth, style])

  return (
    <View style={{ width: $flattenedStyle.width }} onLayout={_onLayout}>
      <Slider
        style={$style}
        onSlidingComplete={_onSlidingComplete}
        value={sliderValue}
        {...restProps}
      />
    </View>
  )
}
```
