### ISSUE TITLE
Please add Range Slider with two(or more) drag thumbs

### ISSUE THREAD

**Issue by AbhiShrek** [callstack/react-native-slider#172]
## Describe the Feature
In many cases, a range input (from - to) is required from users. For example, Age, Distance, Quantity etc. Currently i have to use 2 separate sliders to get the range. It would be nice if react-native-sliders supports range with two drag thumbs.

![Screenshot 2020-04-10 at 5 02 55 AM](https://user-images.githubusercontent.com/11253347/78949216-9cce7980-7ae8-11ea-9f43-c116da937e9c.png)

Refer : 
https://material-ui.com/components/slider/#range-slider

**Comment by Sharcoux** [comment]
I could fix this if my suggestion [here](https://github.com/react-native-community/react-native-slider/issues/169) was considered valid. @michalchudziak  ?

**Comment by Suesanz** [comment]
> ## Describe the Feature
> In many cases, a range input (from - to) is required from users. For example, Age, Distance, Quantity etc. Currently i have to use 2 separate sliders to get the range. It would be nice if react-native-sliders supports range with two drag thumbs.
> 
> ![Screenshot 2020-04-10 at 5 02 55 AM](https://user-images.githubusercontent.com/11253347/78949216-9cce7980-7ae8-11ea-9f43-c116da937e9c.png)
> 
> Refer :
> https://material-ui.com/components/slider/#range-slider
> 
> ## Possible Implementations
> ## Related Issues

Also I think user should have option for a vertical slider also. Making slider vertical should have native implementation.

**Comment by Sharcoux** [comment]
I'm trying to work on this one. I see clearly how it can work for a range (ie 2 thumbs), but can you explain how it is supposed to work for more?

**Comment by inmogr** [comment]
@Sharcoux could you please let us know when can you release 2 thumbs?

**Comment by hwhh** [comment]
+1  - I am trying to use a range selector in "pageSheet" style modal but because in iOS 13 you can swipe down to close the modal a lot of the other range selectors don't work/are very juddery but I realised this slider disables the swipe down to close gesture when being used.

**Comment by Sharcoux** [comment]
Ok, I'll give it a try when I have a few time available. Give me a week or 2.

**Comment by hwhh** [comment]
Great, thank you!

**Comment by hwhh** [comment]
Hi @Sharcoux, 

Just wanted to check in here; I was wondering if you need any help and if so please feel free to let me know!

**Comment by Sharcoux** [comment]
Yeah, I know ^^ I'm working on a project that is being a bit late, but as soon as I finished I'll do the range slider.

**Comment by Sharcoux** [comment]
@hwhh @inmogr @Suesanz @AbhiShrek , Could you try @Sharcoux/slider version 4.0.0?
It includes a range slider.

Please, try also AnimatedSlider and tell me if you notice differences in terms of performances and usage.

**Comment by akinncar** [comment]
@Sharcoux are you implemented here?

**Comment by Sharcoux** [comment]
Well, I can provide the code for web in a fashion that works for all
environments (which is already what I did: the current web implementation
is mine), but until now I didn't receive any answer on my proposal to merge
all implementations into one, so I don't know how to keep improving this
project. For now I have no other way than providing a side project.

**Comment by inmogr** [comment]
Thanks @Sharcoux will try it out

**Comment by Suesanz** [comment]
@Sharcoux, will try out. Thanks!

**Comment by raazatul7** [comment]
Any update on two thumbs on the slider?

**Comment by Sharcoux** [comment]
@raazatul7 Did you try the range slider of @Sharcoux/slider ? Was it not enough for your use case?

**Comment by avlonder** [comment]
@Sharcoux, at least on my Android device, your package doesn't seem to work as expected:
* the thumbs are not rendered
* if I press the track somewhere, the active track color seems to react pretty slow
* you forgot some console.log

I really hope you get the package working. If you can get the same performance as the community package, I (and many others) will definitely use it!

**Comment by Sharcoux** [comment]
@avlonder thanks for the feedback.
The `console.log` issue should be solved in the latest version.
I will definitely try to solve the issues you mention, but it's probably better to discuss this there. Can you open an issue on the project?

**Comment by BartoszKlonowski** [comment]
@AbhiShrek  Thank you for reporting this!
I can see that this is a duplicate of #25 so I'm going to close this one and mark it as a duplicate, so all the work on this enhancement can be tracked from the original issue.

FYI @michalchudziak

**Comment by parthasarathi95** [comment]
import {Slider} from '@miblanchard/react-native-slider';
<Slider
                    minimumTrackTintColor={Colors.themeColor}
                    maximumTrackTintColor={Colors.gray}
                    minimumValue={0}
                    maximumValue={100}
                    thumbTintColor={Colors.themeColor}
                    trackStyle={{backgroundColor:Colors.gray}}
                    value={[low,high]}
                    onValueChange={([low,high]) => {
                      console.log(parseInt(low),parseInt(high));
                      setLow(parseInt(low));
                      setHigh(parseInt(high));
                    }}
                />

**Comment by kfchan-git** [comment]
for anyone who is using `'@miblanchard/react-native-slider'` library. make sure to use render the slider component again if u planning to add actions e.g. reset, to the slider. (otherwise the track's state will not be updated)

**Comment by younes0** [comment]
You can use the RangeSlider component from https://github.com/Sharcoux/slider which works flawless on iOS, Android & Web.
