### ISSUE TITLE
requirenativecomponent:"RNSlider" was not found

### ISSUE THREAD

**Issue by jetBn** [callstack/react-native-slider#189]
why I use show this?

**Comment by leup** [comment]
May be related to this ? 

https://github.com/react-native-community/react-native-slider/issues/152

Have you tried to search in the issues ?

**Comment by BartoszKlonowski** [comment]
@jetBn Can you provide more information?
What is the platform?
What version do you use?
Is the issue still valid if you try it with the latest release?
What are the reproduction steps?

**Comment by BartoszKlonowski** [comment]
Closing due to lack of author's feedback.
