### ISSUE TITLE
[BUG] Clicking on the track doesn't move the thumb sometimes

### ISSUE THREAD

**Issue by misterdev** [callstack/react-native-slider#200]
## Environment
```
System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.16.3
    Yarn: 1.22.4
    npm: 6.14.4
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c
  npmPackages:
    react-native: ~0.61.5 => 0.61.5
```

## Description
Sometimes clicking on the track doesn't move the thumb:
- Android, works perfectly
- Web, works sometimes
- iOS, doesn't work, the thumb moves only if there's a a sliding

### Web
![Screen Recording 2020-07-03 at 15 07 52](https://user-images.githubusercontent.com/11232797/86472838-17054780-bd40-11ea-82ea-0cb1886cb45e.gif)

### iOS
![Screen Recording 2020-07-03 at 16 17 02](https://user-images.githubusercontent.com/11232797/86477802-80d61f00-bd49-11ea-8c37-a710c50682b8.gif)

### Android 👌 
![Screen Recording 2020-07-03 at 16 20 10](https://user-images.githubusercontent.com/11232797/86477877-9ba89380-bd49-11ea-9cbe-1c810a6db78d.gif)

## Reproducible Demo
You can try the web version [here](https://snack.expo.io/@misterdev/[bug]-click-on-track-not-working)

**Comment by castalonirenz** [comment]
Same issue with me.

**Comment by castalonirenz** [comment]
Any updates with this one?

**Comment by PointCodeZero** [comment]
This is not an issue with the library, this is just the native behaviour differences from iOS x Android

**Comment by misterdev** [comment]
Yeah makes sense but the issue on the web version remains.
Also, a way to enable tap on track on iOS would be nice to have

**Comment by agnieszkabugla** [comment]
I have the same issue on iOS.

**Comment by liquid8d** [comment]
Having this issue as well on Windows (in electron) with click events. It seems like a value change is not triggered until after there is any kind of mouse movement post-click. If i click then move the mouse a pixel or two, the click registers.

onSlideStart is called on the click, but the current value is returned and the value isn't adjusted until some movement is detected:

![slider-click](https://user-images.githubusercontent.com/3782076/111076624-6e5cd980-84c3-11eb-926e-43fa79c1e62c.gif)

**Comment by imbarwinata** [comment]
Any updates related to this issue?

**Comment by BartoszKlonowski** [comment]
Hello @misterdev!
The latest versions have the `tapToSeek` implemented, which should be turned on for iOS to work properly when clicking on the slider's track.
Please check on your side with the latest version (*v4.1.6*) if the issue still occurs with the `tapToSeek` set to `true`:
```javascript
<SliderExample tapToSeek={true} />
```

**Comment by BartoszKlonowski** [comment]
Closing due to no response from author and the issue is resolved.
