### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by rectified95** [callstack/react-native-slider#202]
## Describe the Feature
I'm getting started working on the Windows implementation of the Slider component. 
Should push a PR within 2 weeks.
Creating this issue to let the maintainers know of this effort.
Please, assign this one to me, in case I cannot self-assign.

## Related Issues
Closes microsoft/react-native-windows#4612

**Comment by wojteg1337** [comment]
Hello, 
Thanks for letting me know, good luck with implementation!

**Comment by Sharcoux** [comment]
@sharcoux/slider should work just fine with Windows.
Can you try and report?

**Comment by rectified95** [comment]
The Slider implementation recommended by Facebook is this one. Microsoft's effort to increase RN adoption on Windows also relies on the performance provided by native code, hence this choice.

**Comment by chrisglein** [comment]
Looking forward to this!
Implementation looks to be [in PR](https://github.com/react-native-community/react-native-slider/pull/210) and ready to merge soon I hope.

**Comment by BartoszKlonowski** [comment]
@rectified95  Thank you!
