### ISSUE TITLE
[step prop] reason for default value

### ISSUE THREAD

**Issue by rectified95** [callstack/react-native-slider#203]
## What is the reasoning behind the default value for the _step_ property being 0?
In my opinion this is semantically incorrect, as it suggests a slider that cannot be moved at all. Also, this property being optional, it passes a potentially incorrect value to the native platforms. 
Case in point, passing 0 as the step value to the Windows native Slider causes a crash.

I suggest either making this property required, or changing the default value to 0.1 or 1. I can make the change in my upcoming PR adding Windows support for this control.

**Comment by wojteg1337** [comment]
Hello @rectified95,
Please add pr with the fix for Windows, we also could set default value for step. I do not want to make this a breaking chage

**Comment by wojteg1337** [comment]
We have default step for windows which is 1% of range
