### ISSUE TITLE
Two fingers are required to move the slider in accessibility mode

### ISSUE THREAD

**Issue by AnoopN01** [callstack/react-native-slider#214]
## Description

when accessibility is turned on we need two fingers to move the slider, where as if you see the slider to adjust the volume, it works with single finger slider. This is confusing for a blind user using the accessibility mode in his Andorid device This is an issue only in Android. In iOS it works with single finger swipe.

**Comment by Sharcoux** [comment]
If you are aware on accessibilities issues, can you check @sharcoux/slider and tell me if you notice any issue with accessibility on iOS and android? Basically it is the web implementation of this slider made compatible with Android and iOS. And as this lib seems half abandoned, it might be good to have a good alternative.

**Comment by BartoszKlonowski** [comment]
Hello @AnoopN01!
Thank you for reporting this issue. Unfortunately I was unable to reproduce it, so could you please check if the issue you reported still exists on the latest version (*v4.1.7*)?
I would really appreciate a reproduction example/code snippet for this, optionally a demo 🙏

**Comment by BartoszKlonowski** [comment]
Closing due to lack of response from an author and no reproduction.
