### ISSUE TITLE
How to update slider value using ref?

### ISSUE THREAD

**Issue by SahilPawar1994** [callstack/react-native-slider#217]
## Ask your Question

I want to show/update the rating using the slider, when I simply drag the slider, the rating could get updated, To do it I used the value prop of the slider which could give value to the slider but when I do it the slider fluctuates itself. 

To smoothly working, I need to use ref instead of value, so that after getting new data every time, I don't have to use value prop, simply use the ref which could update the value.

Please help me with this?
<img width="304" alt="Screenshot 2020-08-10 at 2 06 05 PM" src="https://user-images.githubusercontent.com/39076268/89764831-c3da9d80-db12-11ea-9dcf-03c096298f9f.png">

**Comment by bharatgupta99** [comment]
https://github.com/react-native-community/react-native-slider/pull/204

**Comment by kg-currenxie** [comment]
@bharatgupta99 that's only for web
