### ISSUE TITLE
size props for thumbImage

### ISSUE THREAD

**Issue by Shing-Ho** [callstack/react-native-slider#225]
## Describe the Feature

We are not controlling the thumbImage size and it's making the ui awful. 

## Possible Implementations

We should be able to control the thumbImage size

## Related Issues

https://github.com/react-native-community/react-native-slider/issues/97
https://github.com/react-native-community/react-native-slider/issues/32

**Comment by bharatgupta99** [comment]
@Shing-Ho For me thumb image is not showing up on android at all.

**Comment by Shing-Ho** [comment]
https://github.com/Shing-Ho/react-native-slider.git
@bharatgupta99 use this library. It's working on both Android and iOS and also it allows you to resize image

**Comment by afilp** [comment]
Can you create a PR to have this here? Seems to be the "official" one community library, this is why.

**Comment by BartoszKlonowski** [comment]
This is a duplicate of #169 so let me close this.
But please track the progress in the original issue.
