### ISSUE TITLE
Slider in a volume like triangle 

### ISSUE THREAD

**Issue by jaikantshikray** [callstack/react-native-slider#243]
i need to implement the slider UI in a volume like triangle how it is possible to design like that 

![image](https://user-images.githubusercontent.com/59036153/98197521-c9485800-1f48-11eb-9626-e7e7a2db1003.png)

**Comment by duttasuraj93** [comment]
@jaikantshikray  please refer to this: [https://github.com/callstack/react-native-slider#thumbimage](url)

you can use the "**thumbImage**" prop and set it to your preferred image. But remember, it only supports local images at the moment.

Eg. 
`<Slider
  thumbImage={require('../../../img/image-icon.png')}
/>`

**Comment by wojteg1337** [comment]
Hello,
there is no option for it on Android,
for iOS, you can use the `trackImage` prop to create any custom track styling
