### ISSUE TITLE
Incorrect cleanup from useLayoutEffect hook. v4.0.0-rc.1 (web)

### ISSUE THREAD

**Issue by ekelund1** [callstack/react-native-slider#244]
## Environment

System:
    OS: Windows 10 10.0.17134
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 4.61 GB / 15.85 GB
  Binaries:
    Node: 14.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 20.0.5594570
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.17763.0
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Visual Studio: 15.9.28307.586 (Visual Studio Community 2017)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

This bug is related to the Web version of the Slider.
RNCSliderNativeComponent.web.js

Created a new empty project with react-native-web and the slider.

Mounted the component, dragging and changing values work.
However when component unmounts it causes a crash caused by a faulty useEffect / useLayoutEffect cleanup function.

Line: 187
`
 React.useLayoutEffect(() => updateValue(initialValue), [
      initialValue,
      updateValue,
    ]);
`

Fixed with:
`
  React.useLayoutEffect(() => {
    updateValue(initialValue);
  }, [initialValue, updateValue]);
`

## Reproducible Demo

Create new react-native project with react-native-web
Add slider

Mount slider
Unmount slider

**Comment by mosoakinyemi** [comment]
Thanks, closing as this has been fixed.
