### ISSUE TITLE
Throttle the value change

### ISSUE THREAD

**Issue by Laurent888** [callstack/react-native-slider#247]
Is there a way to throttle the value from onValueChange? I am setting the value in a state which cause the app to lag because there are too many changes to the state while moving the slider.

**Comment by lukemcgregor** [comment]
I use lodash throttle for this.


```
import { throttle } from 'lodash';

const throttledThing = throttle((
  thing,
  setThing,
) => setThing(thing);

const MyComponent = ({ }) => {

const [thing, setThing] = useState(0);

return (
  ...
    <Slider value={thing} onValueChange={ (val) => throttledThing(val, setThing) } />
  ...
  );
};

**Comment by Laurent888** [comment]
Thanks for your answer, I ended up using this solution !

**Comment by a-eid** [comment]
@Laurent888 please close if this issue is resolved.
