### ISSUE TITLE
tapToSeek iOS prop is not working

### ISSUE THREAD

**Issue by G4BB3R** [callstack/react-native-slider#252]
## Environment

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 1.06 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

tapToSeek iOS prop is not working, false or true, it always allows to set position of the slider cursor, but the value keeps the same.

**Comment by javierbustamante** [comment]
Same here... And the click seems not fire any listener...

**Comment by xmflsct** [comment]
Same here..

**Comment by smallsaucepan** [comment]
Pull request #233 may help with this. Although it's in the documentation, the fix may not have made it in to a release yet.

**Comment by matapo** [comment]
still doesn't work using expo v40 @smallsaucepan

**Comment by smallsaucepan** [comment]
> still doesn't work using expo v40 @smallsaucepan

Does the version of react-native-slider you're using have the fix in it?

**Comment by matapo** [comment]
@smallsaucepan yes, v4.0.0-rc.3

**Comment by smallsaucepan** [comment]
Thanks for confirming @matapo. I'm not super familiar with expo. Is your setup fairly standard? For example, have you had to "eject" to use react-native-slider? And is the behaviour exactly as described above i.e. slider moves but no events get fired that your app can respond to?

**Comment by smallsaucepan** [comment]
Took more of a look at this. Created a new Expo project, ejected, and installed slider@4.0.0-rc.3. Functionality seems to work as expected: tap to seek is ok, and inadvertent sliding while scrolling is fixed too.

Perhaps if more info could be provided about specific setups, we can debug further? @matapo @G4BB3R @javierbustamante

**Comment by matapo** [comment]
> Took more of a look at this. Created a new Expo project, ejected, and installed slider@4.0.0-rc.3. Functionality seems to work as expected: tap to seek is ok, and inadvertent sliding while scrolling is fixed too.
> 
> 
> 
> Perhaps if more info could be provided about specific setups, we can debug further? @matapo @G4BB3R @javierbustamante 

Please try on Expo project that is not ejected

**Comment by mosoakinyemi** [comment]
@matapo could you reproduce this error via an Expo snack and share?

**Comment by matapo** [comment]
@mosoakinyemi here https://snack.expo.io/8n9DPIS7F

**Comment by smallsaucepan** [comment]
Regarding the problem with the label not updating, this behaviour looks like it was introduced in 4.0.0-rc.2, which included fix #235 related to taps.

Paging @MarkCSmith :) Hello mate. Do you think the fix for #235 might be causing taps to be ignored to some degree? For example, sliderTouchStart sets _isSliding to true, but then sliderTouchEnd doesn't get called and the flag is never cleared?

**Comment by MarkCSmith** [comment]
> Hello mate. Do you think the fix for #235 might be causing taps to be ignored to some degree? For example, sliderTouchStart sets _isSliding to true, but then sliderTouchEnd doesn't get called and the flag is never cleared?

I do not think that should happen but I am not 100% sure.  When you say "Regarding the problem with the label not updating" are you referring to https://snack.expo.io/RwhOV4lMH ?  I believe the code in that snack is missing a value prop on the `<Slider>`, e.g., `<Slider value={percent / 1.0} ...`

**Comment by smallsaucepan** [comment]
Thanks for the quick reply Mark. Yes, was referring to the snack provided. I think you're right as running the snack app in a stock RN app seems to work ok.

@matapo Noticed you have used the ScrollView from react-native-gesture-handler in your snack. Was there a reason you didn't use the one that comes with react-native?

By switching the snack to use ScrollView from RN instead, the % labels do now update, so I suspect RNGH ScrollView is doing something odd between the user and the Slider component.

Could you please try the vanilla ScrollView and see what changes that causes?

**Comment by hamzaawais96** [comment]
` "@react-native-community/slider": "4.0.0-rc.3",
   "expo": "^42.0.0",
`
tapToSeek={true} and "onSlidingComplete" doesn't work on this expo version. Any update on it?

**Comment by zabojad** [comment]
`tapToSeek={true}` does not work with `"@react-native-community/slider": "3.0.3" but work with `@next` version

**Comment by BartoszKlonowski** [comment]
I've just tested it with the *example* application and the result is that the `tapToSeek` works as expected:

https://user-images.githubusercontent.com/70535775/131202010-c4a270c9-9e9c-4063-91d7-9e876c2d15ed.mov

@G4BB3R Please check on your side if the reported issue still exists using **the latest version v.4.1.3**.

**Comment by BartoszKlonowski** [comment]
Closing due to no response from author.

**Comment by gibo77** [comment]
> `tapToSeek={true}` does not work with `"@react-native-community/slider": "3.0.3"` but works with `@next` version

IT WORKED FOR ME.

Do this on your RN folder of your project.
What I did is uninstall "3.0.3". npm uninstall @react-native-community/slider –save
Then npm install @react-native-community/slider –save    to get ver4.12
I checked on real device iOS and it worked for me.

**Comment by BartoszKlonowski** [comment]
Glad to hear that, @gibo77!
