### ISSUE TITLE
SliderWindows.vcxproj doesn't get consumed correctly with autolinking for react-native-windows applications

### ISSUE THREAD

**Issue by chrisfromwork** [callstack/react-native-slider#255]
## Environment

* Building on a PC with visual studio 2019
* Using react-native-windows@0.64.0-preview.5
* Using @react-native-community/slider@4.0.0-rc.2

## Description

SliderWindows.vcxproj can be manually linked to enable slider support. Autolinking does not seem to resolve the package/native project correctly. I believe moving forward, autolinking will be the preferred developer experience for consuming windows NativeModules.

## Reproducible Demo

1. Create a react-native-windows project.
2. Add #@react-native-community/slider@4.0.0-rc.2 as a dependency
3. Run `npx react-native autolink-windows --logging` for your project

#### Observed outcome:
SliderWindows.vcxproj does not get added to the project solution file. Its package provider does not get added to the AutolinkedNativeModules.g.cpp file.

#### Expected outcome:
SliderWindows.vcxproj gets added to the project solution file. It's package provider gets added to the AutolinkedNativeModules.g.cpp file.

**Comment by rectified95** [comment]
Created PR https://github.com/callstack/react-native-slider/pull/257

**Comment by rectified95** [comment]
@michalchudziak This one can be closed, PR is merged, I didn't link it in time.

**Comment by BartoszKlonowski** [comment]
@rectified95   Sorry for the delay, but thank you for this!
I will close this issue.
