### ISSUE TITLE
Disabled Prop not working in Web when used with react-native-web

### ISSUE THREAD

**Issue by hpurohit97** [callstack/react-native-slider#261]

**Comment by Sharcoux** [comment]
Can you check if you can reproduce with the last version of @sharcoux/slider (`npm i @sharcoux/slider`)

**Comment by BartoszKlonowski** [comment]
Hello @hpurohit97!
Could you provide this issue with some reproduction example and the environment's information?

**Comment by BartoszKlonowski** [comment]
Closing due to no feedback from an author.
