### ISSUE TITLE
On disable mode For Android platform the player progress color is not visible.

### ISSUE THREAD

**Issue by HITESH122** [callstack/react-native-slider#262]
## Environment

System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 52.14 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 30
      Build Tools: 27.0.3, 28.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: ^0.63.2 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by HITESH122** [comment]
per android native implementation there is no progress colour visible in disabled mode

**Comment by BartoszKlonowski** [comment]
Hello @HITESH122!
The issue you describe is not really a defect, but a default Android platform specific behavior.
Please remember that this library exposes the native implementations of Sliders from various platforms.
If there is a broader need to override this behavior I can transform this bug into a feature request, but it would have to be kept accessible as having Slider disabled should give a clear feedback to user.

**Comment by BartoszKlonowski** [comment]
Closing due to lack of community's interest and details described in the previous comment.
