### ISSUE TITLE
Impossible to change slider position with VoiceOver if it has less than 6 steps configured.

### ISSUE THREAD

**Issue by elfstyle** [callstack/react-native-slider#264]
## Environment

react: 16.13.1 
react-native: 0.63.4

## Description

If the slider is configured with the `step` prop and a number of steps in [min, max] range is less than 6 then it is impossible to change the value using VoiceOver.

## Reproducible Demo
// numberOfSteps = (maximumValue-minimumValue)/step

// Can change the value if  numberOfSteps>=6
`<Slider minimumValue={0} maximumValue={6} step={1} />`

// **Can only increase** the value if  numberOfSteps===5
`<Slider minimumValue={0} maximumValue={5} step={1} />`

// **Can't move slider** if  numberOfSteps<5
`<Slider minimumValue={0} maximumValue={4} step={1} />`

**Comment by dstdnk** [comment]
Hi @elfstyle, are you using bare `react-native` setup, or `expo`?

**Comment by elfstyle** [comment]
> Hi @elfstyle, are you using bare `react-native` setup, or `expo`?
> Are you able to reproduce the issue with the [example app](https://github.com/callstack/react-native-slider/tree/master/example)?

Bare "react-native": "0.63.4"

**Comment by elfstyle** [comment]
Can reproduce on freshly created app https://github.com/elfstyle/SliderA11Y

**Comment by dstdnk** [comment]
@elfstyle unfortunately I could not reproduce your issue.
I used:
```
"@react-native-community/slider": "3.0.3",
"react": "16.13.1",
"react-native": "0.63.4"
```

Here's what I did:
```
npx react-native init reproduce_264 --version 0.63.4 
cd reproduce_264
yarn add @react-native-community/slider
npx pod-install
xed -b ios
```
In the `App.js` I've added:
```
<View
  style={{
    padding: 20,
    height: 300,
    justifyContent: 'space-between',
  }}>
  <Slider minimumValue={0} maximumValue={6} step={1} />   // should work
  <Slider minimumValue={0} maximumValue={5} step={1} />   // should only increase
  <Slider minimumValue={0} maximumValue={4} step={1} />   // should not work
</View>
```
I turned on VoiceOver, tap the slider once to activate it, then double-tap and hold.
While holding I move the slider.

Please let me know if you're able to reproduce the problem with the steps above.

**Comment by dstdnk** [comment]
> Here is the recording
> https://user-images.githubusercontent.com/32192640/114084536-4a03db00-987e-11eb-822d-e1554e18b756.mp4

@elfstyle please let me know the gestures you're using.

**Comment by dstdnk** [comment]
> Can reproduce on freshly created app https://github.com/elfstyle/SliderA11Y

I tried your app:

https://user-images.githubusercontent.com/12425395/114204072-35a10a80-9972-11eb-90a3-3e49ee24c723.mp4

@elfstyle Please let me know the gestures, device (presumably iPad?), iOS version.

**Comment by elfstyle** [comment]
It's working on Samsung s10 as expected.

**Comment by dstdnk** [comment]
@elfstyle ok confirm it's not working with swipe up/down gestures.

**Comment by dstdnk** [comment]
@elfstyle please checkout latest `master` and confirm it's working on your side.
