### ISSUE TITLE
circle slider

### ISSUE THREAD

**Issue by mohamad-1994** [callstack/react-native-slider#267]
I need circle ( half circle ) slider for my project , it should show slider for audio player.
searched many other libraries but almost arent update and didnt work with RN +0.6
( tried for progress bars too, but they are uncontrollable with touches )

can anyone help me to find a solution ? I am newbie in React Native .

I attached what needed from circle slider
![circle slider](https://user-images.githubusercontent.com/61786010/110310211-8641e280-8017-11eb-9156-3336344ebf01.png)

**Comment by wojteg1337** [comment]
Our library does not support circular sliders.
My guess would be to consume https://github.com/bartgryszko/react-native-circular-progress 
and bind it with song progress events to animate the bar.
