### ISSUE TITLE
Add discrete and custom marks

### ISSUE THREAD

**Issue by sn4f** [callstack/react-native-slider#278]
## Ask your Question
Hi!
I am looking for a solution to get a similar effect as on the screen, maybe someone has already done something like this using this package? Something like that https://material-ui.com/components/slider/#custom-marks (but this is on react)
[Screenshot](https://ibb.co/JphLJC7)

**Comment by sn4f** [comment]
I got it

**Comment by Ghassanee** [comment]
Hey sn4f!
Can you share what you got with us.
Thanks!

**Comment by BartoszKlonowski** [comment]
Hello @sn4f!
Can you check if #218 is the same feature you were after?
Would it be also possible to share your findings here?
