### ISSUE TITLE
Release 4.x.x

### ISSUE THREAD

**Issue by Lopatovas** [callstack/react-native-slider#287]
## Regarding release of version 4.x.x

Hello, when is the release for version 4.x.x planned? Currently I can see that it is still a release candidate and I was wondering if you have a schedule for the upcoming release? I would like some features from the new version, mainly the ability to toggle click changes for iOS devices for slider.

Thank you for the library and your time!

**Comment by BartoszKlonowski** [comment]
Hello @Lopatovas, and sorry for the long delay.
We are working on releasing those candidates and we are coming closer, so I'm sure they'll be released very soon.
I will notify you here once this happens.

**Comment by BartoszKlonowski** [comment]
@Lopatovas and everyone interested: v4 is now available.
