### ISSUE TITLE
Sliding back on Android

### ISSUE THREAD

**Issue by ararog** [callstack/react-native-slider#293]
## Environment

System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 218.67 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

I'm using version 3.0.3 of component, no matter what I try, component jumps back to old position.

## Reproducible Demo

Essentially:

const [value, setValue] = useState(initialValue);
<Slider value={value} onValueChange={val => setValue(val)} />

Even if I hard code some value on useState, behavior doesn't change and thumb keeps jumping.

**Comment by nangbanmai1907** [comment]
@ararog how did you fix it? It is problem of me

**Comment by BartoszKlonowski** [comment]
@nangbanmai1907 On which version do you try it?
Can you share your code - how do you utilize `<Slider/>` in your component?
