### ISSUE TITLE
Slider jumps around when used to control react-native-video player.

### ISSUE THREAD

**Issue by avantgardenar** [callstack/react-native-slider#295]
Hi everyone,

I am using react-native-slider as a custom video seeker for react-native-video. 

I am updating the value prop to update the slider position according to the video progress.

But when I try to seek the video, using react-native-slider, and the video progress is updated as the video is running, the slider keeps jumping between the thumb position and the updated video progress.

I tried to handle this by not updating the slider value by setting  a flag on onSlidingStart event, but it is often delayed and the video progress updates before the flag is set.

I tried messing around with the native android code to handle this, but due to my limited knowledge of Android, I couldn't make much progress. Can you point me towars what changes I need to make to the native code for Android, so that the slider does not jump to the position of value prop while the sliding event is active.

Thanks and regards.

**Comment by BartoszKlonowski** [comment]
Hello @avantgardenar!

Can you provide us with reproduction or a link to repository with the app?
What version do you use for this?

**Comment by avantgardenar** [comment]
Hi @BartoszKlonowski ! Sorry for the late erplay, I got busy with work.

I am using version 3.0.3. 

I can't provide a link to the repo, but I am sharing a somewhat similar representation of the issue. Let's say we have a situation like in the code below:

`
import React, { useEffect, useRef, useState } from "react";
import { StyleSheet, Text, View } from "react-native";

import Slider from "@react-native-community/slider";

const Component = () => {
  const [value, setValue] = useState(0);
  const seeking = useRef(false);

  useEffect(() => {
    setInterval(() => {
      if (!seeking.current) {
        setValue((v) => v + 1);
      }
    }, 50);
  }, []);

  const handleSeek = (val: number) => {
    setValue(val);
    seeking.current = false;
  };

  return (
    <View style={styles.container}>
      <Text style={styles.text}>{value}</Text>
      <Slider
        value={value}
        minimumValue={0}
        maximumValue={1000}
        onSlidingStart={() => (seeking.current = true)}
        onSlidingComplete={handleSeek}
      />
    </View>
  );
};

export default Component;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 40,
  },
  text: {
    textAlign: "center",
  },
});

`

Running this would result in something like this:
![issue](https://user-images.githubusercontent.com/69502311/128358627-1366b7a7-ca25-48bd-b928-94ec0f6f985f.gif)

Can you guide me on how to handle something like this?

**Comment by Aravind-Vaidhyanathan** [comment]
> Hi @BartoszKlonowski ! Sorry for the late reply, I got busy with work.
> 
> I am using version 3.0.3.
> 
> I can't provide a link to the repo, but I am sharing a somewhat similar representation of the issue. Let's say we have a situation like in the code below:
> 
> ```
> import React, { useEffect, useRef, useState } from "react";
> import { StyleSheet, Text, View } from "react-native";
> 
> import Slider from "@react-native-community/slider";
> 
> const Component = () => {
>   const [value, setValue] = useState(0);
>   const seeking = useRef(false);
> 
>   useEffect(() => {
>     setInterval(() => {
>       if (!seeking.current) {
>         setValue((v) => v + 1);
>       }
>     }, 50);
>   }, []);
> 
>   const handleSeek = (val: number) => {
>     setValue(val);
>     seeking.current = false;
>   };
> 
>   return (
>     <View style={styles.container}>
>       <Text style={styles.text}>{value}</Text>
>       <Slider
>         value={value}
>         minimumValue={0}
>         maximumValue={1000}
>         onSlidingStart={() => (seeking.current = true)}
>         onSlidingComplete={handleSeek}
>       />
>     </View>
>   );
> };
> 
> export default Component;
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     justifyContent: "center",
>     paddingHorizontal: 40,
>   },
>   text: {
>     textAlign: "center",
>   },
> });
> ```
> 
> Running this would result in something like this:
> ![issue](https://user-images.githubusercontent.com/69502311/128358627-1366b7a7-ca25-48bd-b928-94ec0f6f985f.gif)
> 
> Can you guide me on how to handle something like this?

@avantgardenar Try setting the value prop to some initial value rather than tying it to the state. Ad per the docs, `This is not a controlled component, you don't need to update the value during dragging. `

**Comment by traingethermarc** [comment]
Hi! Have you found a solution :)?

**Comment by avantgardenar** [comment]
Hi @traingethermarc I had to make my own slider using reanimated. You can consult [this](https://thewidlarzgroup.com/reanimated2-slider/) article to do the same.

**Comment by BartoszKlonowski** [comment]
The solution for this would be to provide the react-native-slider with the controlled value property.
This is something that is already reported in #292 and is planned for further releases.

**Comment by richardwu** [comment]
> Hi @traingethermarc I had to make my own slider using reanimated. You can consult [this](https://thewidlarzgroup.com/reanimated2-slider/) article to do the same.

Are you able to share a code snippet of your slider? Much appreciated!

**Comment by avantgardenar** [comment]
> > Hi @traingethermarc I had to make my own slider using reanimated. You can consult [this](https://thewidlarzgroup.com/reanimated2-slider/) article to do the same.
> 
> Are you able to share a code snippet of your slider? Much appreciated!

Hi @richardwu. Sorry I can't do that because it's not my personal project. But the basics of it are covered well in that article. Hope you find what you are looking for.

**Comment by avantgardenar** [comment]
@BartoszKlonowski I am closing the issue as controlled value property is planned in future releases. Thanks!

**Comment by KMouratidis** [comment]
@richardwu @jessemezini not sure if you're still having trouble but here's as small an example as I could make it, using the article avantgardenar linked. I included a `TapGestureHandler` to allow tapping for seek.

<details>
  <summary>Imports & utils</summary>

```javascript
import React from "react";
import { StyleSheet, View } from "react-native";

import Animated, {
  useSharedValue,
  useAnimatedGestureHandler,
  useAnimatedStyle,
} from "react-native-reanimated";
import {
  PanGestureHandler,
  TapGestureHandler,
} from "react-native-gesture-handler";

const SLIDER_WIDTH = 300;
const KNOB_WIDTH = 70;

const clamp = (value, lowerBound, upperBound) => {
  "worklet";
  return Math.min(Math.max(lowerBound, value), upperBound);
};
```
</details>

<details>
  <summary>Slider</summary>

```javascript
const Slider = () => {
  const translateX = useSharedValue(0);
  const isSliding = useSharedValue(false);

  const _onActive = (value) => {
    isSliding.value = true;
    translateX.value = clamp(value, 0, SLIDER_WIDTH - KNOB_WIDTH);
  };

  const onGestureEvent = useAnimatedGestureHandler({
    onStart: (_, ctx) => (ctx.offsetX = translateX.value),
    onActive: (event, ctx) => _onActive(event.translationX + ctx.offsetX),
    onEnd: () => (isSliding.value = false),
  });
  const onTapEvent = useAnimatedGestureHandler({
    onActive: (event) => _onActive(event.x),
    onEnd: () => (isSliding.value = false),
  });

  const scrollTranslationStyle = useAnimatedStyle(() => {
    return { transform: [{ translateX: translateX.value }] };
  });

  const progressStyle = useAnimatedStyle(() => {
    return {
      width: translateX.value + KNOB_WIDTH,
    };
  });

  return (
    <TapGestureHandler onGestureEvent={onTapEvent}>
      <View style={styles.slider}>
        <Animated.View style={[styles.progress, progressStyle]} />
        <PanGestureHandler onGestureEvent={onGestureEvent}>
          <Animated.View style={[styles.knob, scrollTranslationStyle]} />
        </PanGestureHandler>
      </View>
    </TapGestureHandler>
  );
};
```
</details>


<details>
<summary>App & styles</summary>

```javascript

export default function App() {
  return (
    <View style={styles.container}>
      <Slider />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  knobContainer: {
    width: 50,
    height: 50,
  },
  image: {
    ...StyleSheet.absoluteFillObject,
    width: undefined,
    height: undefined,
  },
  slider: {
    height: KNOB_WIDTH,
    width: SLIDER_WIDTH,
    borderRadius: KNOB_WIDTH / 2,
    backgroundColor: "#ddd",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
    elevation: 5,
  },
  progress: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#3f51b5",
    borderRadius: KNOB_WIDTH / 2,
  },
  knob: {
    height: KNOB_WIDTH,
    width: KNOB_WIDTH,
    borderRadius: KNOB_WIDTH / 2,
    backgroundColor: "#757de8",
    justifyContent: "center",
    alignItems: "center",
  },
});
```
</details>

**Comment by richardwu** [comment]
Thanks @KMouratidis! I adapted your code (to include callbacks similar to the existing ones here), as well as a few bugs (`onHandlerStateChange` on `TapGestureHandler`, `simultaneousHandlers` to prevent `Tap` + `Pan` from both firing off):

```
import React, { useEffect, useRef } from "react";
import { View, StyleSheet } from "react-native";

import Animated, {
  useSharedValue,
  useAnimatedGestureHandler,
  useAnimatedStyle,
  runOnJS,
  useAnimatedReaction,
} from "react-native-reanimated";
import {
  HandlerStateChangeEvent,
  PanGestureHandler,
  PanGestureHandlerGestureEvent,
  State,
  TapGestureHandler,
  TapGestureHandlerEventPayload,
} from "react-native-gesture-handler";
import { useTint } from "../theme";

const clamp = (value: number, lowerBound: number, upperBound: number) => {
  "worklet";
  return Math.min(Math.max(lowerBound, value), upperBound);
};

type VideoSliderProps = {
  width: number;
  value: number;
  minimumValue: number;
  maximumValue: number;
  onValueChange?: (value: number) => void;
  onSlidingStart?: (value: number) => void;
  onSlidingComplete?: (value: number) => void;
  knobSize?: number;
  trackSize?: number;
};

const VideoSlider = ({
  width,
  value,
  minimumValue,
  maximumValue,
  onValueChange,
  onSlidingStart,
  onSlidingComplete,
  knobSize,
  trackSize,
}: VideoSliderProps) => {
  const knobSize_ = knobSize ?? 20;
  const trackSize_ = trackSize ?? 8;
  const valueToX = (v: number) => {
    if (maximumValue === minimumValue) return 0;
    return (width * (v - minimumValue)) / (maximumValue - minimumValue);
  };
  const xToValue = (x: number) => {
    "worklet";
    if (maximumValue === minimumValue) return minimumValue;
    return (x / width) * (maximumValue - minimumValue) + minimumValue;
  };
  const valueX = valueToX(value);
  const translateX = useSharedValue(valueToX(value));

  const tapRef = useRef<TapGestureHandler>(null);
  const panRef = useRef<PanGestureHandler>(null);

  // Move slider to current value.
  useEffect(() => {
    translateX.value = clamp(valueX, 0, width - knobSize_);
  }, [valueX]);

  useAnimatedReaction(
    () => translateX.value,
    (cur, prev) => {
      if (cur !== prev && onValueChange) runOnJS(onValueChange)(xToValue(cur));
    }
  );

  const _onSlidingStart = () => {
    "worklet";
    if (onSlidingStart) runOnJS(onSlidingStart)(xToValue(translateX.value));
  };

  // Need to pass xValue since we call this from
  // inside Animated (pan) and in JS (tap), which means
  // in JS translateX.value is not in sync.
  const _onSlidingComplete = (xValue: number) => {
    "worklet";
    if (onSlidingComplete) runOnJS(onSlidingComplete)(xToValue(xValue));
  };

  const _onActive = (value: number) => {
    "worklet";
    _onSlidingStart();
    translateX.value = clamp(value, 0, width - knobSize_);
  };

  const onGestureEvent = useAnimatedGestureHandler<
    PanGestureHandlerGestureEvent,
    { offsetX: number }
  >({
    onStart: (_, ctx) => (ctx.offsetX = translateX.value),
    onActive: (event, ctx) => _onActive(event.translationX + ctx.offsetX),
    onEnd: () => {
      console.log("gesture complete");
      _onSlidingComplete(translateX.value);
    },
  });

  const onTapEvent = (
    event: HandlerStateChangeEvent<TapGestureHandlerEventPayload>
  ) => {
    // Ensure pan did not override.
    if (event.nativeEvent.state === State.ACTIVE) {
      _onActive(event.nativeEvent.x);
      _onSlidingComplete(event.nativeEvent.x);
    }
  };

  const scrollTranslationStyle = useAnimatedStyle(() => {
    return { transform: [{ translateX: translateX.value }] };
  });

  const progressStyle = useAnimatedStyle(() => {
    return {
      width: translateX.value + knobSize_,
    };
  });

  return (
    <TapGestureHandler
      ref={tapRef}
      onHandlerStateChange={onTapEvent}
      simultaneousHandlers={panRef}
    >
      <View
        style={[
          {
            alignItems: "center",
            justifyContent: "center",
            // Add extra transparent height for tapping.
            height: knobSize_,
            width,
          },
        ]}
      >
        <View
          style={[
            styles.slider,
            {
              height: trackSize_,
              borderRadius: trackSize_,
              backgroundColor: tintInactive,
              width,
            },
          ]}
        >
          <Animated.View
            style={[
              styles.progress,
              { backgroundColor: tint, borderRadius: trackSize_ / 2 },
              progressStyle,
            ]}
          />
          <PanGestureHandler
            ref={panRef}
            onGestureEvent={onGestureEvent}
            simultaneousHandlers={tapRef}
          >
            <Animated.View
              style={[
                styles.knob,
                {
                  height: knobSize_,
                  width: knobSize_,
                  borderRadius: knobSize_ / 2,
                  backgroundColor: tint,
                },
                scrollTranslationStyle,
              ]}
            />
          </PanGestureHandler>
        </View>
      </View>
    </TapGestureHandler>
  );
};

const styles = StyleSheet.create({
  slider: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
    elevation: 5,
    justifyContent: "center",
  },
  progress: {
    ...StyleSheet.absoluteFillObject,
  },
  knob: {
    justifyContent: "center",
    alignItems: "center",
  },
});

export default VideoSlider;
```
