### ISSUE TITLE
How to add gradient in slider

### ISSUE THREAD

**Issue by SandyUndefined** [callstack/react-native-slider#301]
Hello,
I m using react-native-slider and I need to add a gradient in the slider.
how to add a gradient in the slider? 

![Screenshot from 2021-08-13 17-26-11](https://user-images.githubusercontent.com/31213192/129366025-8942e47e-707d-4144-a04b-eaa90fa2f6b0.png)
 Help!

**Comment by nileshprajapatihs** [comment]
I want to add gradient in slider same as in above attached image. What is the solution ?

**Comment by SandyUndefined** [comment]
> I want to add gradient in slider same as in above attached image. What is the solution ?

I used `react-native-linear-gradient`. this only applies gradient over the slider and yet the output is what I needed.
