### ISSUE TITLE
Slider 4.1.3 requires React 16.11.0 in conflict with 17.0.2

### ISSUE THREAD

**Issue by cederom** [callstack/react-native-slider#307]
Hello world :-)

I have upgraded React to 17.0.2 and React Native to 0.65.1. Now I cannot install `@react-native-community/slider` 4.1.3 with npm as it requires React 16.11.0..

Please update :-)

**Comment by BartoszKlonowski** [comment]
Hello @cederom,
Thanks for reporting this!

If you use `npm` then you can try installing it with `--force` as a quick workaround. I've just tested it myself and *slider* will work even when *npm* complains.
I will deliver the fix in the meantime.

**Comment by cederom** [comment]
Thank you @BartoszKlonowski for ultra fast response :-)

**Comment by BartoszKlonowski** [comment]
@cederom The latest *v4.1.4* contains the fix for this issue.
Please check and feel free to reopen if it still occurs.

**Comment by cederom** [comment]
Now it installs fine, thank you :-)
