### ISSUE TITLE
pick up interpolated values and integrate with Animated

### ISSUE THREAD

**Issue by misbell** [callstack/react-native-slider#322]
## Describe the Feature

Currently as you drag, you pick up a value from the slider, and the range between the last value you pick up and the next one is  related to how fast you scroll.

I'd like to be able to pick up interpolated values in the rage on an evenlyspaced timed event loop so that I could get smooth animations on related svg graphics - e.g. changing the value on an svg graphics arc as  I am moving the slider thumb.

**Comment by BartoszKlonowski** [comment]
Hello @misbell!
Unfortunately I don't think this is an option - Slider exposes native components which has their props and their "under-the-hood" implementations that we don't want to affect. And to achieve what you described it would be required to modify the outcome of what native components calculates.
I will close this issue as not planned, but let me know if you have anything more in that topic to discuss.
