### ISSUE TITLE
Automate publishing with semantic-release

### ISSUE THREAD

**Issue by michalchudziak** [callstack/react-native-slider#34]
## Describe the Feature

I'd like to automate the publishing process with `semantic-release`. It should be done after https://github.com/react-native-community/react-native-slider/issues/33 is closed.

## Possible Implementations

- Install `semantic-release`
- Run scripts on CI

## Related Issues
https://github.com/react-native-community/react-native-slider/issues/33

**Comment by BartoszKlonowski** [comment]
@michalchudziak I believe that the way we release the package nowadays is completely fine and works well.
Should we keep the idea of having it automated? What would be the benefits of having it automated?

**Comment by michalchudziak** [comment]
I was thinking of some automation for release candidates. Although I'm good with sticking to the current way, as we have proper control over the release process.
