### ISSUE TITLE
Question: Why flow-bin is listed in dependencies?

### ISSUE THREAD

**Issue by kenrick95** [callstack/react-native-slider#340]
## Ask your Question

Hi there, while analyzing my work repository, I found out that this package listed `flow-bin` in `dependencies`. Putting `flow-bin` in `dependencies` causes everyone who installs this package also install `flow-bin` (which ships with a relatively big binary).

I found out that it is introduced in https://github.com/callstack/react-native-slider/pull/210/files#diff-cc5a2f170768969f124108ad3be7fdbcbed774c11774d99a87a3a78fef4ab97bR49 . I wonder if that line was a mistake, since I believe Flow should be used only for type-checking and therefore is sufficient to be listed in `devDependencies` (and not in `dependencies`). 

Thanks

**Comment by BartoszKlonowski** [comment]
Hello @kenrick95, thanks for noticing that!
It's most probably a mistake, and the *flow-bin* is already added into `devDependencies` as well (it's of course required to pass the flow checks).
I believe we can safely remove it from `dependencies`.

**Comment by kenrick95** [comment]
Thanks a lot for the quick response! 👍
