### ISSUE TITLE
Slider doesn't match up with where the mouse is dragging on web

### ISSUE THREAD

**Issue by Powersource** [callstack/react-native-slider#352]
## Environment

Happens on several operating systems. All running inside electron.

## Description

Here are two issue reports that I think are related to this

https://gitlab.com/staltz/manyverse/-/issues/1646

> drag on sliders in setting page and move it to the left, but it goes to the right.

https://gitlab.com/staltz/manyverse/-/issues/1661

> The slider bars in the settings page don't function as expected if I'm zoomed-in (I generally like text to be larger than the default). Specifically, the circle which marks the selected point on the bar is actually in a different place when zoomed. Not a major issue but I figured I'd mention it.

I suspect that this second issue is the same as the first, and that the user just didn't test it unzoomed.

## Reproducible Demo

Happens in production for us https://gitlab.com/staltz/manyverse You can download here but I'll try to create a smaller reproduction https://www.manyver.se/download/ Here's the file where we use the component https://gitlab.com/staltz/manyverse/-/blob/master/src/frontend/screens/settings/view/SliderSetting.ts

**Comment by Powersource** [comment]
I found a fix, slightly hacky though lol https://gitlab.com/staltz/manyverse/-/merge_requests/265/diffs

**Comment by kennethstarkrl** [comment]
Ran into this as well. Was using a state to hide/show the component. After hiding it then showing, the slider position would be off. I fixed this by instead of removing the component, set the opacity to 0 by state.
```jsx
<View style={{opacity : showSlider ? 1 : 0}}>
<Slider/>
</View>
```
the control is still useable even tho you cant see it.. might be able to disable it as well.

**Comment by muni127** [comment]
I am currently hacking my way around this by dispatching a window resize event on mount (with some delay).

Seems like it's not always picking up the correct container size without this.

![image](https://user-images.githubusercontent.com/19216679/187389204-d5c11ddb-291f-4cea-8285-09151fbcf2c6.png)

**Comment by jspizziri** [comment]
@muni127 @Powersource , I'm working on getting web functional in the most recent version. I haven't tested this issue or in electron contexts. If you could test out my PR that could be helpful.

https://github.com/callstack/react-native-slider/pull/462

**Comment by jspizziri** [comment]
@BartoszKlonowski I'm not seeing this in my PR, I'd say that this is fixed by it unless there's more feedback from the people who have chimed in here.
