### ISSUE TITLE
ThumbImage does not work on web

### ISSUE THREAD

**Issue by jakerogers2022** [callstack/react-native-slider#355]

**Comment by yatsyk** [comment]
Looks like it is not implemented on web platform according to package/src/RNCSliderNativeComponent.web.tsx source. As workaround you can provide custom style for thumb view:

**Comment by jspizziri** [comment]
@BartoszKlonowski to me this seems to be a feature request on web rather than a bug.

**Comment by jspizziri** [comment]
Added in https://github.com/callstack/react-native-slider/pull/462
