### ISSUE TITLE
Tap on slider is not triggering onValueChange

### ISSUE THREAD

**Issue by Hellhiem** [callstack/react-native-slider#366]
## Description

**Library Version:** 4.2.1

When you tap on slider value is not changed. 

`onValueChange`  is not triggered at all but UI changes accordingly

**Comment by BartoszKlonowski** [comment]
Hello @Hellhiem, thank you for reporting this!
I will take a look today, but just to confirm: what platform do you encounter this on?

**Comment by MichaelBorde** [comment]
Same issue with React Native `0.65.1` on Android platform.

When I tap on slider I receive `onSlidingComplete`.

When I slide I receive multiple `onValueChange` events and a final `onSlidingComplete` event.
But I noticed that last `onValueChange` has an old value compared to final `onSlidingComplete` event.

**Comment by Hellhiem** [comment]
> Hello @Hellhiem, thank you for reporting this! I will take a look today, but just to confirm: what platform do you encounter this on?

**Comment by Hellhiem** [comment]
> Hello @Hellhiem, thank you for reporting this! I will take a look today, but just to confirm: what platform do you encounter this on?

@BartoszKlonowski 
React Native: 0.67.3

It seems to be Android issue. On iOS when you tap on slider nothing happens for me 

PS Sorry for reopening the issue 🤦

**Comment by BartoszKlonowski** [comment]
No worries!

Nothing happens? You mean that on iOS the thumb does not change its postion after a tap? Did you set `tapToSeek` to `true`?
```javascript
<Slider
  tapToSeek={true}  // for iOS this prop is required for tap to work
/>
```

I will confirm this on my end and will handle that, thank you!

**Comment by Hellhiem** [comment]
@BartoszKlonowski 
Thanks for a reminder. I tested this on iOS and no problems there with `tapToSeek`. This seems to be android issue

**Comment by BartoszKlonowski** [comment]
@Hellhiem I'm glad that helped with iOS. As for the Android - I reproduced the problem and I'll work on it.
Thanks for the patience!
