### ISSUE TITLE
SeekBar on Android is rendering incorrectly in RTL mode

### ISSUE THREAD

**Issue by pavel-stryber** [callstack/react-native-slider#370]
## Environment

**Library Version:** 4.2.1

## Description

1. Slider renders incorrectly on Android in rtl mode. Images how it is now and should be are attached.
2. Currently slider changes it's layout direction based on device language. I want that it was relying on isRTL value of RN instead. It's important in case if we don't have translations for some rtl language and we have to use English as a default.

## Reproducible Demo

<table>
<tr>
<td>
Current behavior:
<img src="https://user-images.githubusercontent.com/44573208/163732628-060f6bd1-f40b-48f0-aec6-60ac1dc7ae22.png" />
</td>
<td>
Correct behavior
<img src="https://user-images.githubusercontent.com/44573208/163732631-dc3bce36-d3b4-481b-93c8-88e6684be01e.png" />
</td>
</tr>
</table>

**Comment by pavel-stryber** [comment]
@BartoszKlonowski thank you for review. When are you going to make a new release?

**Comment by BartoszKlonowski** [comment]
@pavel-stryber I plan to release v4.2.2 not later than end of this week (Friday).
