### ISSUE TITLE
4.2.2 broke android default value

### ISSUE THREAD

**Issue by cristianoccazinsp** [callstack/react-native-slider#377]
## Environment
Android
react-native-slider 4.2.2

## Description
Upgrading from 4.2.1 to 4.2.2 broke the slider's default value. Using `value={3}` (for example), `minimumValue={1}`, and `maximumValue={5}` will render the slider with a default value of 3 on 4.2.1, but 1 on 4.2.2

**Comment by cristianoccazinsp** [comment]
Looks like `onValueChange` is called right after the component mounts (Android only) with the `onValueChange` instead of w/e was set to `value`.

**Comment by BartoszKlonowski** [comment]
Hello @cristianoccazinsp!
Thank you catching this and for the first analysis, I will also check that on my side and provide the hotfix as soon as I find the root cause.

**Comment by wood1986** [comment]
+1. In your example app. the second slider cannot show the right value

**Comment by wood1986** [comment]
Should this be deleted?

https://github.com/callstack/react-native-slider/blob/9e145e5740ff87fbb690a8ce8f7ca1a5332c7567/src/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManager.java#L254

**Comment by BartoszKlonowski** [comment]
@wood1986 Thank you for taking the time to investigate. Did you try removing this and running the example?

**Comment by wood1986** [comment]
Yes, I did before I ask. But I cannot build and run the example on iOS. I filed a bug #381

**Comment by BartoszKlonowski** [comment]
Why trying on iOS if the issue affects the Android platform?

**Comment by wood1986** [comment]
Originally, I wanted to compare with iOS and checked if had the similar issue. 

Agree, this is android thing. 

But I want to double confirm it

**Comment by BartoszKlonowski** [comment]
@wood1986 I will handle the example app today, but in the meantime you can always check the [BartoszKlonowski/rn-slider-repro-app](https://github.com/BartoszKlonowski/rn-slider-repro-app) if the issue has the "*in repro*" label on.

**Comment by hupptechnologies** [comment]
I have also the same issue, when will be fix release for this?

**Comment by JBlaz** [comment]
This happens for me as well on 4.2.0
