### ISSUE TITLE
Please add ability to customise size of thumb and track. 

### ISSUE THREAD

**Issue by adomkawle** [callstack/react-native-slider#382]
Please add ability to customise size of thumb and track. 

thumbStyle and trackStyle can be added to customise height and width of thumb and track.

thanks in advance.

**Comment by BartoszKlonowski** [comment]
Hello @adomkawle!
Thanks for reporting, this is something that indeed is on the potential roadmap (first is to check if it's possible to implement).
However this has already been reported in #92, so I will close this one as a duplicate.
Please track the progress in the original issue.
