### ISSUE TITLE
Setting Current Value of The Slider

### ISSUE THREAD

**Issue by samarthm314** [callstack/react-native-slider#383]
Is there any way to set the value of the slider programmatically? I want to have a reset button that sets the slider back to zero.
Thanks in advance.

**Comment by BartoszKlonowski** [comment]
Hello @samarthm314!
Sure! Version [4.2.0](https://github.com/callstack/react-native-slider/releases/tag/v4.2.0) introduces the controlled `value` property.
Please also take a look at: #349 which implements the controlled value prop.

In case you encounter any issues with it or have any questions, concerns or comments, please feel free to reach out.

I will close this issue as controlled value has already been requested previously and is already provided.
Thank you!

**Comment by BartoszKlonowski** [comment]
@samarthm314 Just in case, please take a look at: #378 #192 and #292
