### ISSUE TITLE
Thumb does not move discretely with step prop set

### ISSUE THREAD

**Issue by CptFabulouso** [callstack/react-native-slider#390]
## Environment

```
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 474.09 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
    Watchman: 2022.05.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

Adding `step={1}` is working in version 4.1.10, but not in 4.2.2 or 4.2.3 (I didn't test other versions), meaning the thumb is not moving (jumping) discretely between 1*N min/max values, but instead moves continuously.

## Reproducible Demo

```
import Slider from '@react-native-community/slider';
import React, { useState } from 'react';

const SliderComponent = () => {
	const [value, setValue] = useState(0);

	return (
		<Slider
			value={value}
			step={1}
			minimumValue={0}
			maximumValue={5}
			onValueChange={setValue}
		/>
	);
};
```

**Comment by BartoszKlonowski** [comment]
Hello @CptFabulouso, thanks for finding and reporting!
Which platform do you observe this on?

**Comment by CptFabulouso** [comment]
Hi. I've tested this on iPhone 11 pro max simulator, not any other device.

**Comment by doganoruc** [comment]
Hello, @BartoszKlonowski is there any update for this issue. I couldn't use the step prop for the discrete movement of the slider. 

Thanks a lot.

**Comment by BartoszKlonowski** [comment]
@doganoruc I plan to deliver the fix in the upcoming week, thank you for you patience!

**Comment by doganoruc** [comment]
Thanks a lot, I have an another question for vertical prop. Is there any problem in there too, for iOS? @BartoszKlonowski

**Comment by ironbat1** [comment]
> BartoszKlonowski
Hi @BartoszKlonowski ,

I hope you are doing well, is there any update on your side,
I really appreciate the work you are doing! Thank you so much.

**Comment by BartoszKlonowski** [comment]
@ironbat1 Thanks for asking, I'm still working on it.
> I plan to deliver the fix in the upcoming week, thank you for you patience!

You can expect a fix (along with some other fixes in 4.2.4) somewhere this week.

**Comment by dhmoon91** [comment]
Hey @BartoszKlonowski Is 4.2.4 supposed to fix this? 

I'm still seeing issue; 
The thumb is not dragging properly based on `step` prop value. Tapping on the slider works properly

I can provide more info if you need.

**Comment by BartoszKlonowski** [comment]
@dhmoon91 Sure! Give me as much details as you can (including platform).
What would be useful is the repro code sample and maybe some recording.
I'll reopen once we got this confirmed.
