### ISSUE TITLE
Can I use the Slider with a width 100% or something like that?

### ISSUE THREAD

**Issue by Knufle** [callstack/react-native-slider#417]
I basically need my slider to fill the entire width of the parent View, is there a way to do it?

**Comment by BartoszKlonowski** [comment]
Hello @Knufle! I'm very sorry for this delayed response.
Currently Slider suffers from a unnecessary padding issue (please see #258) which is tricky to solve, so unfortunately it will be difficult to fill the entire parent, unless some workaround is applied or a change to design of the part of your app where Slider is used.
Please check the issue I linked to see if any response, post, hint given there provides you with at least temporary solution.

**Comment by BartoszKlonowski** [comment]
@Knufle Let me know please if the above answers your question so I know how to handle this item.

**Comment by Knufle** [comment]
Hi! My use case didn't need an absolute 100% width slider, but my description certainly lack that context, however, I was able to achieve my goal without having to do any trick, just regular styles, thank you very much for the help!

**Comment by BartoszKlonowski** [comment]
Great, I'm glad you have your issue resolved!
Let me close this item then.
