### ISSUE TITLE
configure PYTHON_EXECUTABLE when running react-native-slider example app with new architecture.

### ISSUE THREAD

**Issue by jeremyspritelyco** [callstack/react-native-slider#423]
## Ask your Question

I follow the readme and got this error when running android. So how can I add PYTHON_EXECUTABLE when running react-native-slider example app with new architecture?
```
CMake Error at CMakeLists.txt:83 (message):
  Unable to find Python interpreter, required for builds and testing.

  Please install Python or specify the PYTHON_EXECUTABLE CMake variable.```

**Comment by BartoszKlonowski** [comment]
Hello @jeremyspritelyco!
Can you specify which exact version of react-native you're using in your app?
From my understanding Python executable should not be required to run (at least) Slider on new arch, but maybe @cortinico will be able to provide more info/context here and help us.

In the meantime, just in case please provide us with the `npx react-native info`

**Comment by cortinico** [comment]
> @cortinico will be able to provide more info/context here and help us.

@jeremyspritelyco can you provide an overview of your environemnt? Specifically please share the output of `react-native config` and `react-native doctor`

**Comment by BartoszKlonowski** [comment]
Closing due to lack of author's response and not enough details for further investigation.
