### ISSUE TITLE
How to / can use this library on web projects?

### ISSUE THREAD

**Issue by abusada** [callstack/react-native-slider#436]
Hello, it is not clear to me if whether react-native-slider has web support, the docs do say
> For web support please use @react-native-community/slider@next

When I try to use the component with react-native-web I stumble into this issue https://github.com/callstack/react-native-slider/issues/185.

I see that you have a component built specifically for web [RNCSliderNativeComponent.web.tsx](https://github.com/callstack/react-native-slider/blob/main/package/src/RNCSliderNativeComponent.web.tsx) but I don't see any documentation in regards to it, neither do I see that the source code checks which component to use when Slider is imported like so: `import Slider from '@react-native-community/slider';`.

Should the developer decide which component to import? and is `.web` component actively being maintained?

Would adding a [`browser`](https://github.com/defunctzombie/package-browser-field-spec) field to package.json that points to the `RNCSliderNativeComponent.web` component be a possible solution? it seemed to do the trick when I added it on my local machine.

appreciate the hard work and thanks in advance for your help 🙏

**Comment by BartoszKlonowski** [comment]
Hello @abusada!
Thank you for taking the time to reach out.
I have to admit that the support for the web platform has been poor for a long time now, so you may run into problems **but** I plan to revive it and make it high-quality.
I'm always happy to accept PRs on matters that one wants to speed up, and I'm hoping for a patience - the web platform support has not been forgotten or abandoned.

**Comment by jspizziri** [comment]
@abusada @BartoszKlonowski I've created a PR where I'm working on getting web working (want it for a project I'm working on). Any feedback would be appreciated!

https://github.com/callstack/react-native-slider/pull/462
