### ISSUE TITLE
Error while updating property 'step' of a view managed by: RNCSlider

### ISSUE THREAD

**Issue by RnbWd** [callstack/react-native-slider#451]
## Environment

System:
    OS: macOS 13.0
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-27 | ARM 64 v8a, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-29 | ARM 64 v8a, android-30 | AOSP ATD ARM 64 v8a, android-30 | ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-30 | Google APIs ATD ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
## Description

I'm testing my app using the android emulator, API 31 and API 32, and I'm getting this error everytime the Slider component is loaded. I've tried commenting out every single property, or setting the properties to default values, and this error still occurs. I believe this is happening in the android runtime, not in javascript.

![android error](https://user-images.githubusercontent.com/5370305/199150654-6ffc3fa6-2d82-488b-8b9c-b885b2162742.png)

## Reproducible Demo

I'm using the latest version of react-native, 0.70.4, with the latest version of this library 4.3.2

**Comment by scaralfred** [comment]
Having the same issue.

**Comment by cw-shubham-rajput** [comment]
Getting the same issue.

**Comment by BartoszKlonowski** [comment]
@RnbWd The same error is already reported in #437.
Please track the progress in the original item and I will close this one as duplicate.
