### ISSUE TITLE
How to snap to a point on sliding?

### ISSUE THREAD

**Issue by vinay-sayone** [callstack/react-native-slider#456]
Is their any way to snap to a point on this slider ? Also how do we add labels to the snap points like in a step slider ?

**Comment by BartoszKlonowski** [comment]
Hello @vinay-sayone! Can you please elaborate on what you mean by snapping here? Maybe it's the `tapToSeek` you are looking for if you're running on iOS?
As for the second question: The feature of having the step indicator visible is reported in #240 and it is something I'm already investigate with plans to implement in the near future.

**Comment by vinay-sayone** [comment]
@BartoszKlonowski Yea I mean if the slider width is divided into 4 parts and moving the thumb from initial position say 0, after a certain position the thumb will stick to position one, similarly past the position 1, it'll stick to 2. So basically there will be no decimal change values it will be sticking to just 1, 2, 3 etc

**Comment by BartoszKlonowski** [comment]
@vinay-sayone In that case you can just use the `step` property with proper `minimumValue` and `maximumValue`:
```javascript
<Slider
  step={1}
  value={0}
  minimumValue={0}
  maximumValue={3}
  tapToSeek  // enable tap for iOS platform
/>
```
This should exactly match the behavior you described.

As for the step indicator - like I mentioned in previous response - this will be implemented at some point in the near future.

Let me know please if this answer your initial question.

**Comment by BartoszKlonowski** [comment]
@vinay-sayone I'm going to close this for now, but let me know if you have any other questions or issues.
