### ISSUE TITLE
Upper/lower limits not working

### ISSUE THREAD

**Issue by mamonovv** [callstack/react-native-slider#469]
## Environment

System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 10.77 GB / 31.21 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.21.1 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.17 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
  npmGlobalPackages:
    *react-native*: Not Found

## Description

The new upper/lower limits feature doesn't work, the slider goes over those limits easily.

## Reproducible Demo

interface ICustomSlider {
    value: number
    maxPercentage: number
    onValueChange: (value: number) => void
    containerStyles: object
}

const CustomSlider: FCC<ICustomSlider> = ({containerStyles, maxPercentage, value, onValueChange}) => {

    return (
        <View style={[shadows.basic, containerStyles]}>
            <LinearGradient
                start={{x: 0, y: 0}}
                end={{x: 1, y: 0}}
                colors={gradients.cold}
                style={CustomSliderStyles.linearGradient}
            >
                <Slider
                    onValueChange={(v: any) => onValueChange(v)}
                    value={value}
                    step={0.1}
                    upperLimit={20}
                    maximumValue={100}
                    minimumTrackTintColor={'transparent'}
                    maximumTrackTintColor={'transparent'}
                    // thumbStyle={{...CustomSliderStyles.brightThumb, ...shadows.basic}}
                />
            </LinearGradient>
        </View>
    )
};

export default CustomSlider;

**Comment by k0va1** [comment]
+1, had the same issue

**Comment by briandu** [comment]
same on iOS

**Comment by manufdz19** [comment]
+1

**Comment by Szafa99** [comment]
+1 Android and IOS

**Comment by mzdon** [comment]
I see the lowerLimit preventing sliding past the lower limit, but it doesn't prevent me from tapping below the lower limit. The slider will move past the lower limit if tapped.

**Comment by chaitu3399** [comment]
Yes same problem here. Is there any solution to solve that issue
