### ISSUE TITLE
Should this work with Expo?

### ISSUE THREAD

**Issue by VeroLeia** [callstack/react-native-slider#473]
Should the slider work with Expo? It seems to work fine on iOS simulator but running with Expo Go on an android I get requireNativeComponent: "RNCSlider" was not found in the UIManager which I can see happens for other too.

**Comment by massrain** [comment]
Same here with versions of;
Expo SDK 47.0.8
@react-native-community/slider 4.2.4

I also tried in development client build.

**Comment by VeroLeia** [comment]
I have Expo 46.0.16 and @react-native-community/slider 4.2.3, it works in android simulator though, and iOS simulator. Not on an actual Samsung though

**Comment by kaioduarte** [comment]
Rebuilding the dev client build as mentioned in #362 worked for me.

**Comment by BartoszKlonowski** [comment]
@VeroLeia Can you check whether rebuilding fixes the issue you observe?

**Comment by BartoszKlonowski** [comment]
Closing as this issue is most likely resolved on author's side. Please let me know in case of noticing issue again.

**Comment by pjsandwich** [comment]
@kaioduarte when you say rebuild the dev client do mean re-launch metro or create a new dev client build?

**Comment by kaioduarte** [comment]
@pjsandwich recreate the dev client

**Comment by pjsandwich** [comment]
> @pjsandwich recreate the dev client

Can confirm that creating a new dev client build after adding the package to project works for me, simply restarting the bundler as it appears some were able to do did not, hope this helps clarify options for solving this.
