### ISSUE TITLE
Image not rendering on slider

### ISSUE THREAD

**Issue by nakshatrasinghh** [callstack/react-native-slider#478]
## Ask your Question

Why does the image prop not work?

**Comment by BartoszKlonowski** [comment]
Hello @nakshatrasinghh! Is there any specific platform you observe this issue on?

**Comment by nakshatrasinghh** [comment]
Hello @BartoszKlonowski, yes this issue is on web and mobile phone both

**Comment by nakshatrasinghh** [comment]
Any update @BartoszKlonowski

**Comment by nakshatrasinghh** [comment]
Any update @BartoszKlonowski?

**Comment by BartoszKlonowski** [comment]
> Any update @BartoszKlonowski?

I believe this is a duplicate of #346 when it comes to mobile platform.
But when it comes to Web implementation - I'll be happy to see your repro example and more details of this issue (versions you're using, scenario, etc).
