### ISSUE TITLE
Android -> disabled prop can't be toggled

### ISSUE THREAD

**Issue by cgibson-emesent** [callstack/react-native-slider#484]
## Environment

  Binaries:
    Node: 16.17.1
    Yarn: 1.22.19
    npm: 8.15.0
    Watchman: 20220924.070135.0

  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.69.7 => 0.69.7
    react-native-windows: 0.69.14 => 0.69.14

## Description

In the example app `example\src\Examples.tsx` at the `Disabled slider` section, if you toggle the `disabled` prop, it will get stuck on always being active.

E.g
```
  {
    title: 'Disabled slider',
    render() {
      return <SliderExample disabled={true} value={0.6} />;
    },
  },
```
to:
```
  {
    title: 'Disabled slider',
    render() {
      return <SliderExample disabled={false} value={0.6} />;
    },
  },
```
to:
```
  {
    title: 'Disabled slider',
    render() {
      return <SliderExample disabled={true} value={0.6} />;
    },
  },
```
Doing the above enough times will result in the slider being stuck as enabled.

## Reproducible Demo

This is reproducible in the example app.

**Comment by BartoszKlonowski** [comment]
Hello @cgibson-emesent!
Thank you for checking on example app and taking the time to report - I'm surprised I didn't notice that issue, so thanks!
I'll take a look into that.

**Comment by BartoszKlonowski** [comment]
Hello @cgibson-emesent!
Unfortunately I have some troubles reproducing the issue you reported. I'm attaching the video of my tries below, so you can verify if I get the scenario right:

https://user-images.githubusercontent.com/70535775/215532170-1ca730b3-8dc5-4700-95e2-1739c9fd942c.mov

Please let me know if you are able to still see the issue and please post a full repro code so I can try it out.
Just in case: you can always clone the [rn-slider-repro-app](https://github.com/BartoszKlonowski/rn-slider-repro-app) and check this issue on your own setup so we have a common playground.

**Comment by cgibson-emesent** [comment]
Thanks for looking into that @BartoszKlonowski. I'm trying to create a project that reproduces the issue. At the moment though on two projects, the disabled prop isn't working on Android. As in, hard coding `disabled={ true }` doesn't disable the slider. So I'm trying to work out if that's a bug or not.

**Comment by cgibson-emesent** [comment]
@BartoszKlonowski I haven't had a chance to replicate this and I've since moved to another plugin because I needed to change the thumb size and click zone which this plugin doesn't support.
