### ISSUE TITLE
Supposedly missing typescript support (JSX element class does not support attributes...)

### ISSUE THREAD

**Issue by coolersham** [callstack/react-native-slider#488]
## Environment

Not relevant for this kind of issue.

## Description

The following error is generated by the typescript compiler:

`TS2607: JSX element class does not support attributes because it does not have a 'props' property.`

Only the typing seems to be messed up, as the component itself receives all properties correctly.

## Reproducible Demo

1. Create a new react-native project by executing `npx react-native init SliderTestProject`
1. Add this package as a dependency in `package.json` and install it
1. Use the `<Slider />` component in the `App.tsx` file with any attribute

**Comment by BartoszKlonowski** [comment]
Hello @coolersham, thank you for reporting this!
Fortunately one of our contributors - @alpha0010 - already found a fix for that and has launched a PR, so this issue can be fixed by #486

**Comment by cihanbas** [comment]
i'm still getting this issue 
  "react": "16.11.0",
 "react-native": "0.61.3",
    "@react-native-community/slider": "^4.4.2",
