### ISSUE TITLE
Support For Custom Thumb

### ISSUE THREAD

**Issue by mktufan21** [callstack/react-native-slider#491]
## Describe the Feature
 Now we are not able to change add custom thumb where we can insert some dynamic content

**Comment by BartoszKlonowski** [comment]
Hello @mktufan21!
Such feature is already request in #154 and is something I plan to support eventually (no ETA yet though).
Please track the progress in the original issue and let me close this one as a duplicate. In case of any ideas and proposals feel free to also post them in the original issue.
