### ISSUE TITLE
When the step has been set to a number other than 0, the value is always set to zero on iOS.

### ISSUE THREAD

**Issue by KelvinPortuphy** [callstack/react-native-slider#500]
Steps to reproduce the issue (iOS)
1. get the prop to any value like so `step={10}`
2. then `currentValue` to any value by simulating an api with a settimeout.
Result : the current value stays at 0.

here is my code:

<Slider
            disabled={!edittable}
            ref={sliderRef}
            style={styles.slider}
            minimumValue={minValue}
            maximumValue={maxValue}
            tapToSeek={true}
            lowerLimit={!edittable ? currentValue : undefined}
            upperLimit={!edittable ? currentValue : undefined}
            value={currentValue}
            step={10}
            onSlidingComplete={update}
            onValueChange={val => {
              if (edittable) {
                setCurrentValue(Math.round(val));
              }
            }}
            thumbTintColor={edittable ? THEME.ORANGE : THEME.GREY_50}
            minimumTrackTintColor={edittable ? THEME.ORANGE : THEME.ORANGE_TWO}
            maximumTrackTintColor={THEME.GREY_50}
          />

**Comment by BartoszKlonowski** [comment]
@KelvinPortuphy Can you provide me with some more information, so I can try to reproduce the issue? Can you elaborate on what the scenario is that you mention?

**Comment by KelvinPortuphy** [comment]
> @KelvinPortuphy Can you provide me with some more information, so I can try to reproduce the issue? Can you elaborate on what the scenario is that you mention?

I've updated the description 👆

**Comment by BartoszKlonowski** [comment]
Hello @KelvinPortuphy!
I'm not sure if I understand the issue as I can't reproduce it with the scenario you described.
Can you check the repro implementation I linked to this issue and provide me with feedback regarding your issue so we have a common understanding?

**Comment by BartoszKlonowski** [comment]
Closing due to no reproduction possible and no response from author.
Please let me know in case of issue still being valid.
