### ISSUE TITLE
Height of seekbar not inscrease using style

### ISSUE THREAD

**Issue by IsmailJanParacha** [callstack/react-native-slider#507]

**Comment by BartoszKlonowski** [comment]
Hello @IsmailJanParacha!
The height of the seekbar is something that is not yet supported, but is already being open in #85 as a feature request.
Please let me know if you have any more questions.

**Comment by IsmailJanParacha** [comment]
I implement the seek bar for an audio player so when I move the slider means seek bar so they buff a little bit when I move it what's wrong with that?

**Comment by BartoszKlonowski** [comment]
This sounds like a whole different bug, so if you experience some problems while moving the thumb, then please create a new issue with all the details.
So let me close this one, as the feature request is already created and the issue you are now describing should be moved to a new one if you will.
