### ISSUE TITLE
Bar height - Is it possible increase the height of the bar?

### ISSUE THREAD

**Issue by gabrielbarth** [callstack/react-native-slider#526]
I'd like to know if is it possible increase the height of the bar.

From this:
<img width="309" alt="image" src="https://github.com/callstack/react-native-slider/assets/42456106/e4ec99b1-a4e8-4c9f-8db7-1164b7a82f21">

To this:
<img width="309" alt="image" src="https://github.com/callstack/react-native-slider/assets/42456106/eaa7bc52-05f2-49ad-a149-2fe541a6e9e2">

Loking at RNCSliderNativeComponent.web.tsx I could verify that it has trackHeight, but not for Android/iOS.

<img width="749" alt="image" src="https://github.com/callstack/react-native-slider/assets/42456106/637563f5-62d3-45a8-bd7d-4c69946674e0">

Does anyone confirm this?
Thank you for now.

**Comment by upender7270** [comment]
I am also looking for this same feature

**Comment by BartoszKlonowski** [comment]
Hello @gabrielbarth!
The feature you requested is already reported as a feature request in #85.
Let me close this one as a duplicate.
