### ISSUE TITLE
Unable to build on latest version of Xcode | ContextContainer.h not found

### ISSUE THREAD

**Issue by ismdcf** [callstack/react-native-slider#529]
## Environment

* react-native info output:
```
[Codegen] Done.
Analyzing dependencies
RNFBApp: Using overridden static_framework value of 'true'
RNFBMessaging: Using overridden static_framework value of 'true'
Downloading dependencies
Installing RnBugfender 2.2.1 (was 2.1.2)
Generating Pods project
Setting REACT_NATIVE build settings
Setting CLANG_CXX_LANGUAGE_STANDARD to c++17 on /Users/afazsmac/Projects/univiser/uni-buddy-mobile/ios/UniviserBuddyMobileV2.xcodeproj
Pod install took 10 [s] to run
Integrating client project
Pod installation complete! There are 64 dependencies from the Podfile and 77 total pods installed.
afazsmac@Afazss-MacBook-Air uni-buddy-mobile % npx react-native info 
warn Package @ant-design/icons-react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package @ant-design/react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
  OS: macOS 13.5
  CPU: (8) arm64 Apple M1
  Memory: 80.66 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.5.1
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

* are you using the new architecture?
* Yes

* which version of react & react-native are you using?
    "react": "18.2.0",
    "react-native": "0.72.3",

## Description

getting an error while building using the latest version of xcode 

![image](https://github.com/callstack/react-native-slider/assets/16378404/ef861f95-7fc2-4b0d-acc1-76ea7a4baef5)

## Reproducible Demo

I'm using it as a peer dependency with  [AntDesign](https://github.com/ant-design/ant-design-mobile-rn) since I have included it on my project but I'm not using it

**Comment by BartoszKlonowski** [comment]
Hello @ismdcf, thank you for the detailed report 👍 
I will take a look on that!

**Comment by BartoszKlonowski** [comment]
Hello again, @ismdcf!
From what I see in the package.json of `AntDesign` [here](https://github.com/ant-design/ant-design-mobile-rn/blob/e0998c8cd74fe0a69aac27c0a38585c8d977c591/package.json#L56), it is using super old version of Slider, v3.0.3.
This version doesn't have the new architecture support, so when you are trying to compile the `RNCSliderComponent.mm` for new arch, it will search for headers with declarations from React Native for new architecture, which won't be available for lower versions.

Also, I assume you did it, but just in case: please remember to clean the project (`git clean -fxd ios` and/or Cmd+Shift+K in XCode) and reinstall the pods for new architecture (`RCT_NEW_ARCH_ENABLED=1 pod install`) to make sure the new arch is used without old arch or stale deps.

I also did some googling around, and I found this problem having a workaround, described in details [for example here](https://github.com/callstack/react-native-pager-view/issues/743#issuecomment-1656701361), so please check it if maybe it will solve your issue.

If there's anything I missed or don't quite get it yet, please let me know or clarify, so I can further support you.

**Comment by ismdcf** [comment]
Hi @BartoszKlonowski 

Thank you for the heads-up. I was able to build the ios app after adding the required to the podfile. 

inside` post_install do |installer| `block I added the following line 

```
 installer.pods_project.targets.each do |target|
      if target.name == "react-native-slider"
        append_header_search_path(target, "${PODS_ROOT}/../../node_modules/react-native/ReactCommon")
      end
    end
```
