### ISSUE TITLE
Slider with steps indicator, custom thumb component and more to come...

### ISSUE THREAD

**Issue by BartoszKlonowski** [callstack/react-native-slider#539]
This issue (more like a summary/idea of what's to come) collects and implements several requests from our community folks (which is you, who is reading it):
#514 #240 #157 and #154

This means that Slider will soon be extended into a component with additional properties allowing to:
* turn on the steps indicators on the Slider's track
* use your own customized steps indicator
* use your own custom component for the thumb
* what else?

This will introduce a lot of changes, currently all of them are implemented in backward compatibility manner, so it's planned as v4.5.0. So, if you plan to use the Slider with default settings/props, do not worry, nothing will change. And if you want to use the customized steps indicator and stuff, please, give it a try as soon as it's released and provide me with some feedback.

But, before it's launched, there are basically two things you, community can do:
1. Check the work-in-progress branch: [feature/157/slider-steps-indicator](https://github.com/callstack/react-native-slider/compare/feature/157/slider-steps-indicator) to do some initial review, propose some improvement, or just play with the changes already
2. Leave a comment here, suggesting some other ideas, thoughts if you have any, or more importantly:
Suggest the API (props naming, props in general, usage, etc) for the upcoming feature.

Thank you for all the patience and support!

**Comment by Eli-Nathan** [comment]
👋 Thanks for working on this, the big one is the custom thumb component.
Prop name suggestion: `ThumbComponent`
Is there an ETA on 4.5.0 with this feature?

**Comment by BartoszKlonowski** [comment]
Hello @Eli-Nathan, thanks for answering!
For the custom thumb component - No, I can't unfortunately give the ETA. First I have to finish, polish, deliver and potentially fix issues with steps indicator. Only then I can implement the custom thumb. Which will be simpler than the steps indicator (which is a base for further implementations, including custom thumb).
Still, I'm sure it will ship before end of this year.

As for the `CustomThumb` - sounds good! I will definitely consider that, thank you! 👍

**Comment by FacuPerri** [comment]
Hi Guys! Are you going to merge this branch in the near future?

**Comment by BartoszKlonowski** [comment]
Hello @FacuPerri, yes, pretty soon.

**Comment by muhammadsmalik** [comment]
Hi @BartoszKlonowski any updates on this? Thanks.

**Comment by BartoszKlonowski** [comment]
Hello @muhammadsmalik, thanks for asking! I have a delay on this, due to other topics around it, but I still plan to deliver it this Friday (19.01).
