### ISSUE TITLE
Clarification on `onValueChange` Behavior Across Platforms

### ISSUE THREAD

**Issue by landabaso** [callstack/react-native-slider#562]
Hello, and thank you for developing the react-native-slider package. I've been using it in my project and am extremely grateful for its existence.

I've noticed a discrepancy in behavior between the web and native platforms (Android & iOS) regarding the `onValueChange` event. Specifically, I'm uncertain if `onValueChange` should be triggered by programmatic changes to the slider value, as I couldn't find specific documentation on this aspect.

On web,`onValueChange` is called when doing programmatic changes of `value` but not on iOS/Android.

Could you clarify if it's reliable to assume that programmatic changes to the slider value will not trigger the `onValueChange` event? My concern stems from the need to distinguish between user-initiated and programmatic changes.

Upon reviewing the code, I observed that the Android implementation utilizes a `fromUser` flag to differentiate the source of changes, but I didn't find a similar mechanism in the web implementation. Here is the relevant section of the code I was looking at:

https://github.com/callstack/react-native-slider/blob/6f8ee417161cd6ae053aa1f7b1ab783f6ded18a7/package/src/RNCSliderNativeComponent.web.tsx#L148

While I have examined the code, I must admit that I'm not completely familiar with the entire codebase, so I may have missed something pertinent.

Any guidance or clarification you can provide on this behavior would be greatly appreciated.

Thank you for your time and effort in maintaining this package.

**Comment by landabaso** [comment]
After further consideration, I believe this inconsistency actually constitutes a bug. I've submitted a Pull Request for your review: [PR #563](https://github.com/callstack/react-native-slider/pull/563).

**Comment by BartoszKlonowski** [comment]
Yes, this looks like a bug, thank you for taking so much time to investigate! 💪
