### ISSUE TITLE
Callback for component `RNCSlider`

### ISSUE THREAD

**Issue by jleonard99** [callstack/react-native-slider#587]
## Environment

This error occurs in the *Expo Snack web editor*.  Here is a [working snack](https://snack.expo.dev/@jleonard99/sample-rncslider-?platform=web) that DOES NOT throw an error.

## Description

When the [working snack](https://snack.expo.dev/@jleonard99/sample-rncslider-?platform=web) is switched to ["My Device", "Android" or "iOS"](https://snack.expo.dev/@jleonard99/sample-rncslider-?platform=ios) in the Snack editor, the error below is thrown.  Note - when switching to Android or iOS, press the *Launch Snack* button on the emulator to load the app and see the error.

*View config getter callback for component `RNCSlider` must be a function (received `undefined`)*

This is a repost of issue #527.  Issue #527 was closed with this comment: *Closing due to no reproduction possible and no author's response. Also I don't see other community folks having this issue. Feel free to leave a comment if issue is noticed again.*

## Reproducible Demo

1. Follow the [link to the snack app.](https://snack.expo.dev/@jleonard99/sample-rncslider-?platform=web)
2. Change the mode in the top right from *Web* to *Android* or *iOS* or *My Device*.  To use *My Device* you'll need to install *Expo Go* on your mobile device.
3. When selecting *Android* or *iOS*, press the *Launch Snack* button on the emulator to fire up the emulator.
4. When the program is loaded, the error should be displayed.
5. Switching back to "Web" removes the error.

## Use Case

I teach an introductory User Interface course.  I use the *Snack Editor* to highlight different UI widgets and their props in lecture, and to demonstrate quick UI prototypes.  I like the students to follow along and see what the code looks like on their phone using the *My Device* QR code and the *expo go* phone app.  For RNCSlider, the *My Device*, *Android* and *iOS* options throw an error.

**Comment by iwwan-01** [comment]
+1, I've encountered this issue as well.

The snack works in the Expo snack `Web` view, but as soon as I switch to _'My Device', 'Android'_ or _'iOS'_, I am getting the error below.

`View config getter callback for component RNCSlider must be a function (received undefined)`

**Comment by iwwan-01** [comment]
@jleonard99 

Upgrading the following dependencies to their latest versions instead of using the recommended version for SDK 50.0.0, seems to have fixed the issue for me.

```
{
  "dependencies": {
    ...
    "@react-native-picker/picker": "2.7.5",
    "@react-native-community/slider": "4.5.2"
    ...
  }
}
```
