### ISSUE TITLE
Android build failure - C++ errors, buildCMakeDebug

### ISSUE THREAD

**Issue by fractalscape13** [callstack/react-native-slider#594]
## Environment
-My project won't build for Android with 4.5.1. 

* are you using the new architecture? 
Yes

* which version of react & react-native are you using? 
React 18.2.0
React-Native 72.6

## Description

-Install slider package (latest version)

-iOS project works as expected

-Android project fails during build with errors related to:
C/C++: error: no matching constructor for initialization of 'facebook::react::PropsParserContext'
C/C++: error: redefinition of 'RNCSliderMeasurementsManager'
C/C++: error: non-virtual member function marked 'override' hides virtual member function
FAILURE: Build failed with an exception.
* What went wrong: Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.

  3 errors generated.
  ninja: build stopped: subcommand failed.
  
  C++ build system [build] failed while executing:
      /Users/joseph/Library/Android/sdk/cmake/3.22.1/bin/ninja \

**Comment by BartoszKlonowski** [comment]
Hello @fractalscape13, Thank you for reporting!
Looking at your issue I see it should be fixed by #592.
v4.5.2 will include that hotfix and will be released yet today.

**Comment by BartoszKlonowski** [comment]
@fractalscape13 Please check with the latest release v4.5.2.

**Comment by Crhis35** [comment]
Hi @BartoszKlonowski ,  I got this error `FAILED: react-native/android/app/build/intermediates/cxx/Debug/r2z3e13i/obj/arm64-v8a/libreact_codegen_RNCSlider.so`

**Comment by vrnDhmn** [comment]
Getting similar build error for Android
```
C/C++: ld: error: unable to find library -lreact_render_textlayoutmanager
C/C++: ld: error: unable to find library -lrrc_text
C/C++: ld: error: unable to find library -lrrc_textinput
```

**Comment by euliveiras** [comment]
i'm getting a similar error with the android builld:

`* What went wrong:
Execution failed for task ':react-native-community_slider:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-community_slider:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /home/euliveiras/Android/Sdk/platforms/android-34/core-for-system-modules.jar.
         > Error while executing process /usr/lib/jvm/java-21-openjdk/bin/jlink with arguments {--module-path /home/euliveiras/.gradle/caches/transforms-3/b2efd9b1599c64ee71e5520b19dc895b/transformed/output/temp/jmod --add-modules java.base --output /home/euliveiras/.gradle/caches/transforms-3/b2efd9b1599c64ee71e5520b19dc895b/transformed/output/jdkImage --disable-plugin system-modules}`

**expo version:** 50.0.14
**react-native:** 0.73.6
**@react-native-community/slider:** ^4.3.0
