### ISSUE TITLE
 Unable to resolve module react-native/Libraries/NativeComponent/ViewConfigIgnore

### ISSUE THREAD

**Issue by raochenghui** [callstack/react-native-slider#596]
## Environment
Android
![image](https://github.com/callstack/react-native-slider/assets/70825629/582790ed-4a2b-47ce-905e-4a6b9cbd20c1)

* react-native info output:
```
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800U with Radeon Graphics
    Memory: 1.04 GB / 14.83 GB
  Binaries:
    Node: 20.12.0 - 
    Yarn: 1.22.22 - 
    npm: 10.5.0 - 
    Watchman: 20240310.093207.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.22000.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 17.0.10 
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

* are you using the new architecture?

* which version of react & react-native are you using?
react-native@0.68.2

## Description
```bash
Error: Unable to resolve module react-native/Libraries/NativeComponent/ViewConfigIgnore from D:\project\APP\huangdao\hd_zhdd_app\node_modules\@react-native-community\slider\dist\RNCSliderNativeComponent.js: react-native/Libraries/NativeComponent/ViewConfigIgnore could not be found within the project or in these directories:
```
![image](https://github.com/callstack/react-native-slider/assets/70825629/36d05da6-8255-442f-953f-8a2f456679d1)

**Comment by raochenghui** [comment]
react-native version 0.68.2 does not have this `ViewConfigIgnore.js`  file
![image](https://github.com/callstack/react-native-slider/assets/70825629/f3bd3313-8df9-405d-a826-f2380bc7cce0)

I switched the @react-native community/slider library to 4.5.0 to fix it

**Comment by mirabo-trunghoang** [comment]
It is the same error when I tried to install with iOS, Xcode build log:
```
Error: Unable to resolve module react-native/Libraries/NativeComponent/ViewConfigIgnore from /Path/to/my/project/node_modules/@react-native-community/slider/dist/RNCSliderNativeComponent.js: react-native/Libraries/NativeComponent/ViewConfigIgnore could not be found within the project or in these directories:
  node_modules
```
package version: 4.5.2
MacOS 14.4
npm version 6.14.18
Xcode 15.0

**Comment by SatyamReactNative** [comment]
> react-native version 0.68.2 does not have this `ViewConfigIgnore.js` file ![image](https://private-user-images.githubusercontent.com/70825629/323448829-f3bd3313-8df9-405d-a826-f2380bc7cce0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MzEyMzYsIm5iZiI6MTcxNDYzMDkzNiwicGF0aCI6Ii83MDgyNTYyOS8zMjM0NDg4MjktZjNiZDMzMTMtOGRmOS00MDVkLWE4MjYtZjIzODBiYzdjY2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA2MjIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3Y2VjMWYyMjk4NTcxNjRhZDNiZjQxMjEyMTJiYWMyMTJmZjliYWQ0MWNkYWFjNjgzZjQwZWI1ZWEzMDY1YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mC2ZucknCRaoi-aQorUDWiHvcx2g_0zCu-BIkbBgV8c)
> 
> I switched the @react-native community/slider library to 4.5.0 to fix it

This is working. 
I changed from ^4.5.0 to 4.5.0 and now it it working. Thank you @raochenghui

**Comment by FrancRodrix** [comment]
still same error

**Comment by draggie** [comment]
@FrancRodrix could you provide your` react-native info` output and some more details about the error ?
