### ISSUE TITLE
Invariant Violation: View config getter callback for component `RNCSlider` must be a function (received `undefined`)

### ISSUE THREAD

**Issue by lokeshphilips** [callstack/react-native-slider#604]
Invariant Violation: View config getter callback for component `RNCSlider` must be a function (received `undefined`)
I am facing below issue while trying to integrating into React Native application 

`Invariant Violation: View config getter callback for component `RNCSlider` must be a function (received `undefined`).`

_Originally posted by @lokeshphilips in https://github.com/callstack/react-native-slider/issues/330#issuecomment-2149346430_

**Comment by Joe-Altrai** [comment]
How to solve this? im also facing the same issue in new expo project

**Comment by za-rakib** [comment]
rm -rf node_modules           # Delete node_modules
npm install                   # Reinstall dependencies
npm start --reset-cache       # Clear Metro cache and start the server
cd ios && pod install         # Reinstall CocoaPods dependencies

**Comment by Joe-Altrai** [comment]
Thanks, but i figured that already. It was my mistake that idk that when installing a native module in expo needs a development build, so after building a development build has resolved that.

**Comment by draggie** [comment]
Closing this issue as there have been no further reports and it seems to no longer be present. If this problem resurfaces or you encounter a related issue, please feel free to open a new issue or comment here. 
Thanks for your contribution and for helping improve the project!
