### ISSUE TITLE
Slider fail build in New Arch

### ISSUE THREAD

**Issue by mensonones** [callstack/react-native-slider#610]
## Environment

* react-native info output:
```
System:
  OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  Memory: 20.15 GB / 31.12 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 20.12.2
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.4
    path: /usr/local/bin/yarn
  npm:
    version: 10.5.0
    path: /usr/local/bin/npm
  Watchman:
    version: 4.9.0
    path: /usr/bin/watchman
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.7
    wanted: 0.73.7
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

* are you using the new architecture?
yes

* which version of react & react-native are you using?
React 18
React Native 0.73.7

## Description
1 - Make new project React Native 0.73.7
2 - Install Library: yarn add @react-native-community/slider
3 - Modiffy gradle.properties: newArchEnabled=true
4 - Running project and get error 

![Captura de tela de 2024-06-18 17-58-29](https://github.com/callstack/react-native-slider/assets/5387202/442535b4-4052-4b7b-b206-8f566f64f1db)

## Reproducible Demo

https://github.com/mensonones/ReproducibleSliderBugNewArch

**Comment by draggie** [comment]
Fixed with https://github.com/callstack/react-native-slider/pull/597
