### ISSUE TITLE
StyleSheet.compose() deprecated

### ISSUE THREAD

**Issue by kholland950** [callstack/react-native-slider#614]
react-native-web has deprecated `StyleSheet.compose()`
https://github.com/necolas/react-native-web/releases#:~:text=%5Bchange%5D%20Deprecate%20StyleSheet.compose().%20Use%20style%20array%20syntax.

I saw that a previous PR (#563) removed usage of `compose()` for this deprecation, but a subsequent PR (#555) re-added the usage of `compose()`.

We are upgrading react-native and are now receiving a deprecation warning.

## Environment
* which version of react & react-native are you using?
react: 18.3.1
react-native: 0.74.2
react-native-web: 0.19.10

## Description

We are receiving the warning: `StyleSheet.compose(a, b) is deprecated; use array syntax, i.e., [a,b].`
<img width="544" alt="Screenshot 2024-06-26 at 1 44 53 PM" src="https://github.com/callstack/react-native-slider/assets/8575132/a049283f-5450-46c1-99e5-25b9e3b98a5f">

## Reproducible Demo

Any usage of `Slider` results in the warning.
```
    <Slider
      maximumTrackTintColor={trackTintColor}
      minimumTrackTintColor={trackTintColor}
      thumbStyle={styles.thumb}
      thumbTintColor={thumbTintColor}
      style={props.style}
      {...props}
    />
```

**Comment by BENJAMINmlp** [comment]
who's head is side bar in

**Comment by totallytotallyamazing** [comment]
I've been having this exact same issue for some time now. Any new updates to this bug issue?
Thanks!
