### ISSUE TITLE
Slider not working if it is in an absolute positioned container

### ISSUE THREAD

**Issue by omerts** [callstack/react-native-slider#619]
## Environment

* react-native info output:
```
Sorry for some reason react-native info is stuck on my system
```

* are you using the new architecture? No

* which version of react & react-native are you using?
  "react-native": "0.73.1"
  "react": "18.2.0",

## Description

When the slider is inside an container which has `position: absolute;` the slider is unresponsive.

## Reproducible Demo
```
import React, {useState} from 'react'
import {View} from 'react-native'

import Slider from '@react-native-community/slider'

export const Test: React.FC = React.memo(() => {
  const [zoom, setZoom] = useState<number>(0)

  return (
    <View style={styles.container}>
      <Slider
        value={zoom}
        onValueChange={setZoom}
        step={0.1}
        minimumValue={-1}
        maximumValue={1}
      />
    </View>
  )
})

export const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 20,
    right: 20,
    flexDirection: 'row',
    gap: 26,
  }
})

export default CameraController
```

**Comment by folin03** [comment]
+1

**Comment by draggie** [comment]
@omerts I was trying to reproduce this, however maybe you are missing some more context cause just putting the slider into absolutely positioned container does not cause issue you have described.

Please provide working reproduction example so I will be able to investigate that.

**Comment by Parsa-29** [comment]
same problem here

**Comment by nudge411** [comment]
same problem here
