### ISSUE TITLE
Add renderAboveThumbComponent 

### ISSUE THREAD

**Issue by KKKaisar** [callstack/react-native-slider#623]
## Describe the Feature

Add renderAboveThumbComponent rect above thumb when it is in pan.  Feature should be like in main image in https://github.com/miblanchard/react-native-slider?tab=readme-ov-file
## Possible Implementations

If renderAboveThumbComponent is set then it is shown when thumb is panned(dragged).
```jsx
<Slider 
renderAboveThumbComponent = {()=><Image src={src} />}
/>
```

**Comment by BartoszKlonowski** [comment]
Hello @KKKaisar!
I see this is a duplicate of #605, so let me close this one.
Thank you!
