### ISSUE TITLE
Add track marks in slider

### ISSUE THREAD

**Issue by KKKaisar** [callstack/react-native-slider#624]
## Describe the Feature

Add track marks in slider, a rects with height litlle higher than slider line, little width and different color. Feature can be seen in main image in https://github.com/miblanchard/react-native-slider?tab=readme-ov-file
## Possible Implementations

trackMarks property that takes array of number values, which will be coordinate of each marks place on slider
```jsx
<Slider
trackMarks=[
0.283,//mark one
0.897,//mark two
]
/>
```
. trackMarksColor and trackMarkHeight and trackMarkWidth, or all of this can be replaced with on trackMarkStyle

**Comment by BartoszKlonowski** [comment]
Hello @KKKaisar!
Some time ago there was a release of `StepMarker` and `renderStepNumber`. I'm aware this is not exactly what your request is for, so I will keep that in backlog, but please check those out and see if you can utilize those already.
Thank you for the idea 👍
