### ISSUE TITLE
'react/renderer/components/rncore/EventEmitters.h' file not found on react-native 0.75, new Arch

### ISSUE THREAD

**Issue by efstathiosntonas** [callstack/react-native-slider#631]
## Environment

* react-native info output:
```
System:
  OS: macOS 14.6.1
  CPU: (20) arm64 Apple M1 Ultra
  Memory: 969.91 MB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.16.0
    path: ~/.nvm/versions/node/v20.16.0/bin/node
  Yarn:
    version: 4.4.1
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.3
    path: ~/.nvm/versions/node/v20.16.0/bin/npm
  Watchman:
    version: 2024.08.26.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/stathis/.gem/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
    System Images:
      - android-25 | Google APIs ARM 64 v8a
      - android-27 | Google APIs ARM 64 v8a
      - android-28 | Google APIs ARM 64 v8a
      - android-29 | Google APIs ARM 64 v8a
      - android-30 | Google APIs ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.4
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

```

* are you using the new architecture? YES

* which version of react & react-native are you using? react 18.3.1 and rn 0.75.2

## Description
 I'm experiencing a build issue on react-native@0.75.2 and new Arch: `'react/renderer/components/rncore/EventEmitters.h' file not found` on `RNCSliderShadowNode` when using   `@react-native-community/slider": "4.5.2"`

What I did but no luck: 
1. pod deintegrate
2. rm -rf node_modules
3. yarn install
4.  RCT_NEW_ARCH_ENABLED=1 pod install
5. build on xcode

see attached screenshot: 
![Screenshot 2024-09-02 at 15 32 31](https://github.com/user-attachments/assets/7679ffba-e820-41ca-b5e5-06bef4120e76)

**Comment by efstathiosntonas** [comment]
it seems that after changing the import to: `#include "EventEmitters.h"`  from `#include <react/renderer/components/rncore/EventEmitters.h>
` it built fine.

**Comment by arstropica** [comment]
I am getting the error on `<react/renderer/components/rncore/EventEmitters.h>` not found.
![Screenshot 2024-09-04 at 3 41 30 PM](https://github.com/user-attachments/assets/ade3910f-6ab8-459d-aa37-542974013b7d)

**Comment by arstropica** [comment]
The following header search path seems to be missing from my pod build settings. When I add it manually, the error goes away.

```
${PODS_CONFIGURATION_BUILD_DIR}/React-FabricComponents/React_FabricComponents.framework/Headers/react/renderer/components/rncore
```

**Comment by Shakahs** [comment]
The current release, 4.5.3, does not include this fix and so iOS NewArch does not build.

**Comment by wjaszczuk** [comment]
hi @BartoszKlonowski. I've checked 4.5.3 on the RN 0.75.3 with the new architecture, and this bug still exists.

**Comment by BartoszKlonowski** [comment]
Yes, the latest release does not yet include the fix for that issue.
This (along with some other topics) will be released soon, I hope for your patience.
Thank you!

**Comment by shay-te** [comment]
Hello. Thank you so much. 
I am experiencing the same issue. When can we expect a fix? If downgrade to what version? Will this work?
