### ISSUE TITLE
Missing "Installation in bare React Native projects" mentioned in Expo docs

### ISSUE THREAD

**Issue by conor909** [callstack/react-native-slider#651]
The installation documentation on the [expo docs](https://docs.expo.dev/versions/latest/sdk/slider/#installation) mentions information in the ReadMe to help install into managed projects but its missing

**Comment by BartoszKlonowski** [comment]
Hello @conor909!
From what I can see, this sentence is generic in the Expo docs, and applies (is displayed) for each and every library listed in "Expo SDK" section. This sentence is generated from here: https://github.com/expo/expo/blob/main/docs/components/plugins/InstallSection.tsx
I'm afraid it is up to the Expo maintainers to address this however they see fit, and this issue should be moved to Expo's repo. I will close this one as it doesn't really apply to this package.

As for installing this package in bare React Native projects, everything is described in [Installation & Usage section](https://github.com/callstack/react-native-slider?tab=readme-ov-file#installation--usage) of the README for the Slider project.

However, if you encounter any issue installing this project please feel free to reach out by creating new issue.

Thank you!
