### ISSUE TITLE
Does this build warning cause any problems?

### ISSUE THREAD

**Issue by luisnaranjo733** [callstack/react-native-slider#663]
## Ask your Question
For react native windows projects, there is an MSBuild warning that happens for all projects that consume this library (including the example project in this repo).

How to reproduce

1. Open example solution in Visual Studio
2. Build and watch output logs

Error is below (and occurs several times)

1>C:\code\react-native-slider\example\node_modules\react-native-windows\PropertySheets\External\Microsoft.ReactNative.Cpp.ProjectReferences.props(12,5): **warning MSB4011**: "C:\code\react-native-slider\example\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" **cannot be imported again. It was already imported at** "C:\code\react-native-slider\example\node_modules\@react-native-community\slider\windows\SliderWindows\**SliderWindows.vcxproj (80,5)". This is most likely a build authoring error. This subsequent import will be ignored.**

```
Build started at 2:55 PM...
1>------ Build started: Project: example, Configuration: Debug x64 ------
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Error occurred while restoring NuGet packages: File C:\code\react-native-slider\example\windows\example\packages.config does not exist.
1>Determining projects to restore...
1>C:\code\react-native-slider\example\node_modules\react-native-windows\PropertySheets\External\Microsoft.ReactNative.Cpp.ProjectReferences.props(12,5): warning MSB4011: "C:\code\react-native-slider\example\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" cannot be imported again. It was already imported at "C:\code\react-native-slider\example\node_modules\@react-native-community\slider\windows\SliderWindows\SliderWindows.vcxproj (80,5)". This is most likely a build authoring error. This subsequent import will be ignored.
1>Done building project "SliderWindows.vcxproj".
1>All projects are up-to-date for restore.
1>Determining projects to restore...
1>C:\code\react-native-slider\example\node_modules\react-native-windows\PropertySheets\External\Microsoft.ReactNative.Cpp.ProjectReferences.props(12,5): warning MSB4011: "C:\code\react-native-slider\example\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" cannot be imported again. It was already imported at "C:\code\react-native-slider\example\node_modules\@react-native-community\slider\windows\SliderWindows\SliderWindows.vcxproj (80,5)". This is most likely a build authoring error. This subsequent import will be ignored.
1>Done building project "example.vcxproj".
1>C:\code\react-native-slider\example\node_modules\react-native-windows\PropertySheets\External\Microsoft.ReactNative.Cpp.ProjectReferences.props(12,5): warning MSB4011: "C:\code\react-native-slider\example\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" cannot be imported again. It was already imported at "C:\code\react-native-slider\example\node_modules\@react-native-community\slider\windows\SliderWindows\SliderWindows.vcxproj (80,5)". This is most likely a build authoring error. This subsequent import will be ignored.
1>- Checking auto-linked files...
```

Does this warning have any impact, and should it be fixed?
It sounds like perhaps removing line 80 in SliderWindows.vcxproj may do this

**Comment by BartoszKlonowski** [comment]
Hello @luisnaranjo733, good question!
No, this will not impact any development experience, nor the application/lib in any way. This is the matter of dependencies being downloaded for each.
I don't want to dive into details, but what I will suggest is to check if other libs has the same warning, and if yes - reach out to React Native Windows team from Microsoft, Their knowledge is huge and I'm sure they'll be much more helpful 💪 
If that does not happen for any other lib you try, reach out to me again so I can take a look if this is something I can improve in the Windows-related build of this package.

I will close this issue just to keep it clean, but Thank you for reaching out and let me know.
