### ISSUE TITLE
Vertical Slider on Android Nougat

### ISSUE THREAD

**Issue by hernandezChristian9** [callstack/react-native-slider#69]
## Description

Hi, I've tried to rotate the slider to vertical using "transform:rotate" and it show me this. I've tested this on Samsung Galaxy S7 edge on Android Nougat.

Any thoughts about why this is happening?

## Reproducible Demo

![ezgif-4-1084633681e9](https://user-images.githubusercontent.com/6622170/57688596-6a19c800-7670-11e9-8ddb-c53b2d05ae33.gif)

**Comment by michalchudziak** [comment]
Does it happen on other OS versions?

**Comment by hernandezChristian9** [comment]
No, only in this version

**Comment by BartoszKlonowski** [comment]
It looks like it is already fixed by PR #101 and it can be closed.
Checked for version 3.0.3:
![Vertical-2](https://user-images.githubusercontent.com/70535775/129242604-fe91dfa6-674d-4007-97a9-115cb627a6ab.gif)
