### ISSUE TITLE
[ios] Setting thumbImage doesn't work if thumbTintColor is also set

### ISSUE THREAD

**Issue by markymc** [callstack/react-native-slider#78]
## Environment

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 511.48 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 19, 20, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 19.1.0, 22.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 1.3.0
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.3.2
```

## Description

I have just upgraded from RN 0.57.7 to RN 0.59.9 and alongside it moved to this version of Slider due to the deprecation warnings. I noticed that my thumb image had stopped working on iOS, and after some debugging realised that if I commented out the `thumbTintColor` it would then use the image correctly. However, of course I need the tint for Android, so I've worked around it with a `Platform.select`, but this doesn't seem ideal. 

## Reproducible Demo

Broken:
```
    <Slider
      thumbTintColor={PRIMARY_COLOR}
      ...
      thumbImage={require('../../assets/images/icons/playback-position.png')}
    />
```

`thumbImage` doesn't render.

Working:

```
    <Slider
      thumbTintColor={Platform.select({ ios: null, android: PRIMARY_COLOR })}
      ...
      thumbImage={require('../../assets/images/icons/playback-position.png')}
    />
```

`thumbImage` renders.

**Comment by BartoszKlonowski** [comment]
@markymc This issue is really old and seems to be outdated.
Can you please check if this issue still occurs on the latest release v4.1.1?

**Comment by markymc** [comment]
@BartoszKlonowski I'm afraid I'm not working on the project that was using this library any more, and don't really have the time to check this now, sorry. Perhaps you can close it, and if anyone else reports this problem in newer versions you could reopen it?

**Comment by BartoszKlonowski** [comment]
No worries, I can close it then.
Thank you for the response! 👍
