### ISSUE TITLE
trackStyle and thumbStyle

### ISSUE THREAD

**Issue by Moji0098** [callstack/react-native-slider#92]
in past version that depricated we have two property **trackStyle** and **thumbStyle** , but in this version of **react-native-slider** we have not this feature !! what do i for change thumb and track style ? :((

**Comment by michalchudziak** [comment]
Can you provide me the output of your `react-native info`? Also, keep in mind that these properties are supposed to work only on iOS.

**Comment by Moji0098** [comment]
[android linking](https://facebook.github.io/react-native/docs/native-modules-android)
this link have good expression for linking package to project . help me

**Comment by jocoders** [comment]
Good day! Can you tell me please how can i change the thumb size?

**Comment by Technaur** [comment]
@michalchudziak is there any way you can change the track style? Like how heigh/thick the track is, or if the track can have a border, etc..

**Comment by dbilgin** [comment]
I was wondering about these features too, why were they removed?

**Comment by tmaly1980** [comment]
I actually don't see those props mentioned in the react-native core docs. Perhaps you're thinking of this third party library?

https://github.com/jeanregisser/react-native-slider

**Comment by dbilgin** [comment]
@tmaly1980 you are right, but it seems like that library is getting deprecated and not very active. Is there any chance we could get these capabilities here?

**Comment by tmaly1980** [comment]
@dbilgin I'd assume since it's mostly native, that there would be Java/Swift code involved. There is this other library available that seems more recent (haven't tried yet):

https://azir.io/docs/components/core/slider

**Comment by dbilgin** [comment]
@tmaly1980 thank you, I haven't seen this one, I'll try it out!

**Comment by tmaly1980** [comment]
@dbilgin Works beautifully for me!

**Comment by thinklinux** [comment]
They were not removed because these features were never there. I will speculate here but probably it's not that easy to add if the native sliders of iOS and Android don't support much in terms of styling the thumb.

**Comment by Sharcoux** [comment]
https://github.com/react-native-community/react-native-slider/issues/169

**Comment by dindustack** [comment]
Please, team kindly add the styling features for the slider thumb. Thanks

**Comment by daddou-ma** [comment]
After taking a look at the Code, I've found that we `thumbStyle`, `thumbSize`, `trackHeight` properties that are not mentioned in Readme.md Doc. maybe this could help.

Here is a PR containing README.md updates [#481](https://github.com/callstack/react-native-slider/pull/481)

**Comment by Sharcoux** [comment]
Hum... I'm afraid that those props are actually available only on the web implementation that I did. If you want to use them on mobile, use [this](https://github.com/Sharcoux/slider). We maintain it at my company.

**Comment by daddou-ma** [comment]
@Sharcoux Didn't notice that. I'm closing the PR. Thank you

**Comment by BartoszKlonowski** [comment]
Closing in favor of #40
