### ISSUE TITLE
iOS thumbTintColor causes handle to offset slightly

### ISSUE THREAD

**Issue by Kikketer** [callstack/react-native-slider#96]
## Environment

System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 1.13 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 22, 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.1
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.3 => 0.60.3

## Description

Not sure if this is a regression or even if it's new to this new community edition.  But I noticed on iOS when I set the tint color of the thumb, it'll pull the slider to the right slightly.

![Tint-Color-iOS](https://user-images.githubusercontent.com/958042/62384750-e22db680-b518-11e9-9617-02079eb8e368.png)

Ignore the tick marks, that's my own doing and not related.

## Reproducible Demo

```
<Slider thumbTintColor={'orange'} />
```
vs
```
<Slider />
```

**Comment by schumannd** [comment]
experiencing similar issues. Did you end up finding a workaround?

**Comment by Kikketer** [comment]
@schumannd yeah I simply did some fancy work with padding and margins to shrink up the left side "tail" on the slider.  It's not perfect or even pretty but it works.

**Comment by spinosajoseph** [comment]
This particular prop was also causing me issues on iOS. This logic helped resolve my issue:

thumbTintColor={ !IS_IOS ? color : undefined }

**Comment by BartoszKlonowski** [comment]
Hello @Kikketer!
Unfortunately I wasn't able to reproduce the issue you reported.
Please check my example app linked to this issue (BartoszKlonowski/rn-slider-repro-app) to check the repro example on your own.
But, just to have the common point of view, please see the screenshot below:
<img width="1229" alt="obraz" src="https://user-images.githubusercontent.com/70535775/163589211-16eb9d64-0a99-4939-9bf0-292adeba71f5.png">

I can see that this issue has been reported on very outdated version now, so I believe this issue has been already fixed at some point.
I believe I can close this issue, but I will add the label waiting for your response just in case you would like to double check on your side (using the latest version).

Thank you!

**Comment by Kikketer** [comment]
Feel free to close. I don't see myself testing for this bug in a reasonable amount of time.

If it comes up again I'll open a new ticket. Thanks.

**Comment by BartoszKlonowski** [comment]
Thank you for the fast replay!
